### ISSUE TITLE
Direct communication with the community?

### ISSUE THREAD

**Issue by Xh4H** [microsoft/BosqueLanguage#100]
I think Bosque would be better if there was a channel where we could directly ask questions - offer different perspectives since this project, as I understood it, needs the feedback of the community.

Modern options are Slack - Discord.

What do you think?

**Comment by Hritam-cse** [comment]
There should be a channel to ask questions and different problems with this language.

**Comment by hearot** [comment]
There's a chat on Telegram. https://t.me/BosqueLanguage

**Comment by Xh4H** [comment]
> There's a chat on Telegram. https://t.me/BosqueLanguage

Is it official though?
