### ISSUE TITLE
What is considered a "long signature"

### ISSUE THREAD

**Issue by Xh4H** [microsoft/BosqueLanguage#104]
Related to the latest commit bf9920a89bc52badc2ecdf82249ffd22a2312b49, [point 0.15.5](https://github.com/Microsoft/BosqueLanguage/blob/master/docs/language/overview.md#0.15.5-Method-Arguments), what is considered a long singature? 

Are we talking about a fixed amount of characters? 80? 60?

**Comment by mrkmarron** [comment]
I would read this as a situational decision that can be adjusted. These are intended as a starting point and can be refined as we move forward.
