### ISSUE TITLE
what is problem of my code?

### ISSUE THREAD

**Issue by hesamkaveh** [Microsoft/BosqueLanguage#105]
What is problem of code below?

```
namespace NSMain;

function allOdd(...args: List[Int]): Bool {
    return args->all(fn(x) => x % 2 == 1);
}


entrypoint function main(): Bool {
    return allOdd(1, 3, 4);
}

```

**Comment by Xh4H** [comment]
allOdd expects a list of Int's, therefore you need to pass that:

```
namespace NSMain;

function allOdd(...args: List[Int]): Bool {
    return args->all(fn(x) => x % 2 == 1);
}


entrypoint function main(): Bool {
    var intList = @[1, 3, 4];
    return allOdd(intList);
}
```

**Comment by hesamkaveh** [comment]
> allOdd expects a list of Int's, therefore you need to pass that:
> 
> ```
> namespace NSMain;
> 
> function allOdd(...args: List[Int]): Bool {
>     return args->all(fn(x) => x % 2 == 1);
> }
> 
> 
> entrypoint function main(): Bool {
>     var intList = @[1, 3, 4];
>     return allOdd(intList);
> }
> ```

`Parse error -- ["main.bsq",9,"Type error"]`

**Comment by Xh4H** [comment]
Excuse me, what was the initial error you were getting?

**Comment by hesamkaveh** [comment]
For the first code i got below error:
```  hesam@hesam-pc  /tmp/BosqueLanguage/ref_impl   master ?  node bin/test/app_runner.js main.bsq                                      1 ↵  10034  15:03:59
Reading app code...
Parse error -- ["main.bsq",3,"Invalid lambda type"]
```
And for your code i got this error:
```
Reading app code...
Parse error -- ["main.bsq",9,"Type error"]
```

**Comment by mrkmarron** [comment]
Hi @hesamkaveh, thanks for opening the issue and sorry for any confusion this has caused. It looks like there is a bug in the lambda type inference for invocations. I'll open an issue and get on that.

While that is in progress the code will work if you give the explicit types on the lambda:
```
function allOdd(...args: List[Int]): Bool {
    return args->all(fn(x: Int): Bool => x % 2 == 1);
}
```

You can call this in one of two ways.

Create a list and then spread it:
```
entrypoint function main(): Bool {
    var intList = List[Int]@{1, 3, 4};
    return allOdd(...intList);
}
```

Or give the parameters individually:
```
entrypoint function main(): Bool {
    return allOdd(1, 3, 4);
}
```
