### ISSUE TITLE
How to print anything to command line?

### ISSUE THREAD

**Issue by shubhamgoel4aug** [Microsoft/BosqueLanguage#107]
**I would like to print something on the console but I am curious about how to. For example: we have Console.WriteLine("Text"); in C#, so something similar in Bosque?**

Can you show a sample of code for this?

**Comment by jakalkhalili** [comment]
We can only do this now by:

```
entrypoint function main() : String {
   return "Hello world!";
}
```

In future I think we'll get a better way to print something on console.

**Comment by Hritam-cse** [comment]
Bosque does not support any IO e.g. for printing/accepting input as of now.

**Comment by mrkmarron** [comment]
Commit #116 adds a special keyword `_debug` to support printing out info during debug and in the future repl activities:
```
entrypoint function main() : None {
   _debug("Hello world!");

    return none;
}
```
