### ISSUE TITLE
Interest in Bosque subreddit?

### ISSUE THREAD

**Issue by farleykr** [microsoft/BosqueLanguage#109]
Right now there's a small community limited to this repo.  A subreddit could help generate interest and build up the Bosque community.

I have little to no experience with programming language design, implementation, etc.  I'd rather not go rogue but if @mrkmarron is on board with the idea I'd love to get a subreddit started as a way to help out aside from working on the language itself.

**Comment by Xh4H** [comment]
This would suit better in #100. I do agree there should be some channel to talk about the language.

**Comment by abhinavsagar** [comment]
@farleykr @Xh4H @mrkmarron How about starting a gitter channel?

**Comment by mrkmarron** [comment]
I am a bit bandwidth constrained so would have limited participation but I have no objections to anyone setting up a channel on reddit/gitter/etc. to discuss things. We can always pull the conversation back to the repo if there is a need.

**Comment by hearot** [comment]
@farleykr Awesome! I'd join it

**Comment by farleykr** [comment]
Done!  https://www.reddit.com/r/bosquelang/ has been created!
