### ISSUE TITLE
Unit Testing library for Bosque

### ISSUE THREAD

**Issue by jakalkhalili** [microsoft/BosqueLanguage#110]
I started writing unit testing framework for Bosque (in Bosque of course).
Limitations of Bosque current state made me difficult to write simple assertion functions.
Lack of reflection functions, no support for coding in multiple files is the weak point of Bosque for now.

I called this library Bsquit. 
Repository: [jakalhalili/Bsquit](https://github.com/jakalkhalili/Bsquit)
I'll update this library when issue #110 will be fixed to provide assertion functions. 
I'm waiting now for support coding in multiple files. 

Feel free to use.

**Comment by mrkmarron** [comment]
Assuming this has lost momentum. Please reopen if needed.
