### ISSUE TITLE
Is performance priority? 

### ISSUE THREAD

**Issue by khoshroomahdi** [Microsoft/BosqueLanguage#113]
I know it's experimental but my question is performance is your priority to design this languages? Could bosque comete with C in the future?

**Comment by mrkmarron** [comment]
Hi, yes performance is important in this project. Our first goal is the functionality of the language so performance is not an initial priority. 

However, many of the language features that simplify reasoning have the potential to enable compilation techniques and opportunities that are not really practical in a lanugage like C++ or Java. In our [tech report](https://www.microsoft.com/en-us/research/uploads/prod/2019/04/beyond_structured_report_v2.pdf) (section 5) we do a (small hand example) of how the simplifications in Bosque enable the SIMD optimization of a loop that would not be realistically doable in other languages. Our [previous experience](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/07/SimdSynth.pdf) has shown these types of transformations can speed-up hot loops by easily 2x-4x. This is just one example and I think there are many other exciting opportunities around performance.

**Comment by khoshroomahdi** [comment]
Awesome
