### ISSUE TITLE
What Bosque Language can build in the future?

### ISSUE THREAD

**Issue by ChristianWijayaPakis** [microsoft/BosqueLanguage#119]
**What problem would this feature solve? Please describe and, if possible, provide an example.**

**Do you have a proposed solution? If so please share it.**

**Describe alternative solutions you've considered**

**Additional context**

**Comment by abhinavsagar** [comment]
This can be closed.

**Comment by wandyezj** [comment]
I'm not sure I understand the question?

@ChristianWijayaPakis would you mind elaborating?
