### ISSUE TITLE
Consider adding reference cells or similar explicitly mutable types

### ISSUE THREAD

**Issue by sirosen** [Microsoft/BosqueLanguage#12]
Apologies if there's something like this already on the spec, but I didn't see it if so. Coming from the SML world, ref cells allow you to explicitly break the immutability rule.

This is costly for all the obvious reasons, but it allows for datatypes like the SML/NJ Queue.

**Comment by mrkmarron** [comment]
Thanks, at this point I think we want to avoid mutable state in the language. There may be options for some linear/ownership type support in the future but this will require some careful thought/design.
