### ISSUE TITLE
[String].includes still errors

### ISSUE THREAD

**Issue by Xh4H** [Microsoft/BosqueLanguage#123]
**Describe the bug**
Checking whether a string contains a substring errors. Supposedly fixed for #111, apparently not.

**To Reproduce**
Code used:
```
namespace NSMain;

entrypoint function main(): Bool {
    var test = "abc";

    return test.includes("a");
}
```

**Expected behavior**
Return true

**Screenshots**
https://i.imgur.com/w5i0Gm1.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Bosque Version: master branch

**Comment by clegoz** [comment]
You need to use `->` for invoke expressions.

I've tried this one and it is working:
```
namespace NSMain;

entrypoint function main(): Bool {
    var test = "abc";

    return test->includes("a");
}
```

**Comment by Xh4H** [comment]
Oh, I see. Thank you.
