### ISSUE TITLE
Functor example

### ISSUE THREAD

**Issue by khoshroomahdi** [Microsoft/BosqueLanguage#129]
I want to know how can i code without loop? I need example ( for loop, foreach, while, and do while side by side) in bosque language.

**Comment by raphaelkieling** [comment]
Recursion

**Comment by raphaelkieling** [comment]
- [Funcional programing loop](https://www.quora.com/Why-dont-pure-functional-programming-languages-provide-a-loop-construct)
- [while-loops-with-a-functional-programming](https://stackoverflow.com/questions/43592016/how-do-i-replace-while-loops-with-a-functional-programming-alternative-without-t)
- [Recursion Wikipedia](https://en.wikipedia.org/wiki/Recursion)

Something functions created to help `filter`, `map`...
- [Concep filter,map,reduce in javascript](https://medium.com/poka-techblog/simplify-your-javascript-use-map-reduce-and-filter-bd02c593cc2d)
