### ISSUE TITLE
Tilde symbol

### ISSUE THREAD

**Issue by Dersei** [microsoft/BosqueLanguage#13]
The language itself sounds very interesting, however I would like to mention that tilde symbol `~` in my opinion isn't a very good choice. I know that there are plenty of programming languages that use this symbol, but it's not very easy to type on, for example, Polish, Swedish, Finnish and Danish keyboards. It's not in natural position, in some cases it has to be followed by other key to appear and it is also used to make special characters. For instance `~`+a in Polish gives ą. I'm pretty sure it isn't even shown on some Italian keyboards.

**Comment by mrkmarron** [comment]
Hi Dersei, thanks for opening the issue. I saw this opinion in some of the other online commentary as well so it definitely deserves consideration and discussion.

Thanks

**Comment by hearot** [comment]
I'm Italian and I've got an Italian keyboard. I totally agree. By the way, I've edited my keyboard and added the tilde symbol, but most Italians won't do that.

**Comment by odalet** [comment]
In the same field, it's worth noting that the back quote is particularly painful on French keyboards (tilde is okay though). I noticed it wasn't part of the language (yet). May it remain so.

**Comment by orcmid** [comment]
Um, yes, we need to deal with natural-language regimes that have ~, ` (and ^) as non-spacing keyboard codes for composed characters.  I see I have violated the ` rule, but a grammar I have allows ' in the concrete (plaintext) syntax as synonymous with `.

**Comment by mrkmarron** [comment]
Closing as this is now covered in the syntax discussion.
