### ISSUE TITLE
Interfaces or similar to provide object-less methods

### ISSUE THREAD

**Issue by Xh4H** [microsoft/BosqueLanguage#132]
**What problem would this feature solve? Please describe and, if possible, provide an example.**
Allowing the creation of interfaces which would provide methods that do not need an initialized object to provide funcionality.
E.g. Math class.

**Describe alternative solutions you've considered**
I am using entities as of now, but they are not meant to be used for this, imo.

**Comment by mrkmarron** [comment]
Bosque provides `concept` for this purpose. Concepts can declare *and* define fields, static methods, etc. The type checker is not complete here so we need to pay attention to uses of things like diamond inheritance etc. when we use them (as the checker might not complain).
