### ISSUE TITLE
Documentation None Coalescing example is incorrect

### ISSUE THREAD

**Issue by hahn-kev** [Microsoft/BosqueLanguage#137]
If you look at the current example for [None Coalescing](https://github.com/Microsoft/BosqueLanguage/blob/master/docs/language/overview.md#5.24-None-Coalescing) it shows this:
```
function default(x?: Int, y?: Int) : Int {
    return (x ?| 0) + (y ?| 0); //default on none
}
default(1, 1) //2
default(1)    //1
default()     //0

function check(x?: Int, y?: Int) : Int? {
    return x ?& y ?& x + y; //check none
}
default(1, 1) //2
default(1)    //none
default()     //none

```

If you look at the second section it's calling default again with the same arguments but different return values, I think it should be calling check to show how that's working.

**Comment by mrkmarron** [comment]
You are absolutely right. I have corrected the documentation. Thanks.
