### ISSUE TITLE
Is some kind of HTTP Client API planned? Would it be useful?

### ISSUE THREAD

**Issue by catchmareck** [microsoft/BosqueLanguage#138]
I was wondering if there are plans to implement some sort of Http Client API to make HTTP requests. If so, is it going to be part of the core library? If there are no plans for it yet, would it be useful? What do you think?

I'm thinking of some entity, called `HttpClient` for instance, which would provide basic CRUD operations: `post`, `get`, `put` and `delete`.

**Comment by mrkmarron** [comment]
Hi, this might be an interesting experimental host design (see issues #75 and #68). If we had a simple JSON style format that did some express like routing that would allow building some simple applications like you mention.

```
{
    get: [
        {route: "/foo/", action: "NSMain::foo", args: []},
        {route: "/bar/:id", action: "NSMain::bar", args["id"]},
        ...
    ],
    post: [
        ...
    ],
    ....
}
```

Alternatively, if we were more ambitious here, we could try a host that integrated with a serverless provider hooks like AWS Lambda or Azure Functions.
