### ISSUE TITLE
Over-promising/-reaching?

### ISSUE THREAD

**Issue by orcmid** [microsoft/BosqueLanguage#151]
Thank you for undertaking this investigation.  It gives rise to and provides a forum for some interesting and challenging questions.  That you have undertaken it with design and code in-the-open is terrific.  I am already learning much from this effort.  I wish you great success in this experiment.

Please take these remarks as "devil's advocacy" in search of understanding how such an effort fits into the Microsoft Research portfolio and broadly becomes a contribution to Computer Science and Information Technology application.

I have made foolish speculations, envisionings, and proposals over the course of my career.  I notice that some kinds of argument/reasoning are easy to overlook, especially when I want it all to be true.  So, I'm all for what is envisioned for Bosque, and I realize I don't see how the magic is intended to be established as having happened.  

Concerning the README.

> The Bosque programming language is a Microsoft Research project that is investigating language designs for writing code that is simple, obvious, and easy to reason about for both humans and machines. 

Cool.  It is an investigation.  I wonder what the research report of any conclusions would look like, and what the findings would be with regard to such empirical determinations with respect to _obvious_ and _easy to reason about_,  and for whom?  We could wonder the same thing about _simple_, which means _very_ different things to different people.  Researchers might not be representative of the community for which we desire these qualities to be experienced in practice.

>The key design features of the language provide ways to avoid accidental complexity in the development and coding process.

**Uh Oh**.   This statement sort of presumes the outcome of the investigation, that the way to  design a language with such quality is known.  I assume _accidental_ is sort of Aristotelian around the distinction between the essence/essential and the accidental/incidental stuff that one might have to contend with, like learning a specific syntax that one is compelled to use to express ideas and operations that are simpler to express at a higher (informal) level.  

I suspect one needs to talk about the on-ramp and progression to fluency, what it means for having use of a language ready-to-hand, and how we are trained to the use of artifacts despite their accidental qualities, only disconcerting when different accidental qualities confound us.   I do recognize the tendency to confuse "the known" with "the simple."  And essential is not necessarily handy.  There seems to be no consideration of the social aspects of programming and the languages that communities adhere to for whatever purposes.

> The result is improved developer productivity, increased software quality, and enable a range of new compilers and developer tooling experiences.

I'm not certain one can expect so much of a programming language, but if that is achievable, how are we to know this has been accomplished and what is it attributable to?  Setting aside Total-Cost-of-Ownership questions (a theme at Microsoft in competitive settings), how are these qualities measurable, and what is their relative merit with respect to other arrangements?

It would be interesting to have early input from folks (also at MSR, I suspect) who concern themselves with ethnography and also education.  

I repeat.  Thank you for undertaking this investigation.  It gives rise to and provides a forum for some interesting and challenging questions.  That you have undertaken it with design and code in-the-open is terrific.  I am already learning much from this effort.

**Comment by khoshroomahdi** [comment]
Good questions

**Comment by wandyezj** [comment]
I've notices that languages tend to borrow and learn from each others advantages and disadvantages overtime.

Would it make sense to compile a list of know issues that make things hard for developers in prevalent Moden Programming languages:

* Python
* JavaScript
* TypeScript
* C++
* C#

Some Examples:

* Types are nice, the lack of types in Python and JavaScript makes it difficult to define clear interfaces between components. That said, Python and JavaScript lack of required specified types makes it somewhat convenient to write quick scripts. TypeScript seems to offer a middle ground where Types can often be determined by the arguments and Intellisense and compiler support can offer feedback to the developer to prevent common mistakes.
* Many older languages have diverse coding conventions, where different communities use different conventions to represent the same thing (Perl is a particular offender). The diversity of ways to represent the same thing makes it difficult for developers to read other developers code. Recently there has been an effort to define ISO C++ standard conventions to make it easier for developers to share and understand each others code while preventing common mistakes. Would it make sense for a new language to enforce a style up front as part of the language that is designed to prevent common mistakes, and make it easier for everyone in the community to understand each others code. Once nice feature of Python for example is that it enforces consistent spacing within a block.
