### ISSUE TITLE
Create a fancy icon

### ISSUE THREAD

**Issue by Chris2011** [Microsoft/BosqueLanguage#153]
**What feature do you think could be better?**
It would be nice, if we can have a first draft of a fancy icon for Bosque 😊

**Why do you think the current design is unsatisfactory? Please provide a code example if possible.**
Wo don't have one atm 😁

**Do you have a proposed alternative design?**
Not really, I can ask my designer, maybe we need a bit more context about it to create one.

**Comment by raphaelkieling** [comment]
Duplicate of #94

**Comment by Chris2011** [comment]
Sry for the duplicate, I searched for icon, but not for logo 😅

**Comment by raphaelkieling** [comment]
oh sorry, but I think the logo can discuss in #94 but open it if you think different :smile:

**Comment by Chris2011** [comment]
No everything is fine :). Thx for linking it. Logo is good to go, Icon can look the same IMO.
