### ISSUE TITLE
Selamat malam bosQue

### ISSUE THREAD

**Issue by nggit** [microsoft/BosqueLanguage#156]
Maybe you should make a page on wikipedia. Misdirected to https://en.wikipedia.org/wiki/Basque_language

**Comment by orcmid** [comment]
See the rules on Wikipedia about who contributes on a particular topic and the constraints thereon.  @nggit could do it.

**Comment by orcmid** [comment]
PS: An useful part of such an account is the basis for the name, Bosque.
