### ISSUE TITLE
How do I create a recursive function?

### ISSUE THREAD

**Issue by emosGambler** [microsoft/BosqueLanguage#159]
**Please describe what you want to do**
I want to create a resursive fibonacci function

**What I try to do in Bosque**
![image](https://user-images.githubusercontent.com/20873814/57178399-a890d500-6e6f-11e9-8cbb-73affe01c6ba.png)

**What I see in console**
![image](https://user-images.githubusercontent.com/20873814/57178406-b8101e00-6e6f-11e9-9738-a3e9d69b09fe.png)

**Comment by emosGambler** [comment]
When I have removed `rec` from all the place (and fixed fibonacci code lol) then it gives me correct result:

![image](https://user-images.githubusercontent.com/20873814/57178691-c44aaa00-6e74-11e9-930e-aea2307d7d36.png)

Are the docs outdated?

**Comment by catchmareck** [comment]
I think it's not implemented yet. See #27

**Comment by khoshroomahdi** [comment]
The result is wrong. 832040 is not fibonacci series.

**Comment by emosGambler** [comment]
Let me sum this up:
1) `rec` is not implemented
2) you can do a recursive function without `rec`
3) docs are misleading, because they show you not implemented features

@khoshroomahdi, I checked the result for x = 30 on three different online tools and it gave me the same result.

**Comment by khoshroomahdi** [comment]
I make mistake.

**Comment by raphaelkieling** [comment]
But, why i would use `rec` if that not need to work?  That is to explicit the recursive function?
