### ISSUE TITLE
Misleading information in docs - List declaration

### ISSUE THREAD

**Issue by emosGambler** [microsoft/BosqueLanguage#160]
**Describe the bug**

I tried this code:

`
entrypoint function main(): List[Int] {
    var n: List[Int] = List@{1, 2, 3};
    return n;
}
`

**and was getting this message:** 
fail with exception -- TypeError: Cannot read property 'invoke' of undefined

**so I've added `[Int]` before declaring what is in list, like this:**

`
entrypoint function main(): List[Int] {
    var n: List[Int] = List[Int]@{1, 2, 3};
    return n;
}
`

and the code runs just fine.

**So couple of issues:**
1) Error message does not show in which line it occurs and what exactly should be done
2) There are errors in docs, like here:

![image](https://user-images.githubusercontent.com/20873814/57190857-86ef2680-6f1f-11e9-8b94-dc5bf38196a6.png)

or here:

![image](https://user-images.githubusercontent.com/20873814/57190867-966e6f80-6f1f-11e9-91ab-4083593295b0.png)

Correct me if I'm wrong.

**Comment by mrkmarron** [comment]
Hi, sorry about the confusion there. Thanks for opening the issue.
