### ISSUE TITLE
Extra Data Structures and Comparable concept

### ISSUE THREAD

**Issue by emmet-m** [microsoft/BosqueLanguage#174]
**What problem would this feature solve? Please describe and, if possible, provide an example.**
`collections.bsq` currently doesn't contain a stack, queue, priority queue, tree, etc. These are pretty common data structures that the language could use.

The language however currently uses the notion of `Indexable` for key-based equality, which is well and good for collections such as lists, sets, etc. but wouldn't seem to work for priority queues, trees, etc. as we need some form of comparison, not just equality. Comparing ints, guids and strings are easy enough but things get complicated when we need to compare records, tuples, etc.

**Do you have a proposed solution? If so please share it.**
We could create a comparable concept, and allow such data structures like so:

```none
concept Comparable { 
     // Standard, compare() : Int function
    abstract static compare(first: Some, second: Some): Int;
}

entity Int provides Some, Parsable, Comparable {
    // ...
    override static compare(first: Int, second: Int) {
        if (first == second) {
            return 0;
        }
        return first < second ? -1 : 1;
    }
}

entity Tree[T where Comparable] provides Collection[T] { ... }
```
(Note: I'm pretty sure the above isn't type correct as the arguments to compare() aren't contravariant, but it would be nice if we could do this. Is there any way to make something like this using generics?)

How does equality work in Bosque for entities as well? I figured == works as normal for the standard types, but how does it behave for entities? Would we need an Equatable concept or does this work out of the box?

**Describe alternative solutions you've considered**
Potentially making Comparable derived from Indexable, however the two concepts seem too disjoint to me (as Indexable is about key-based indexing and comparison, rather than general object comparison).

Another consideration is to make an Enum of Lt, Gt, Eq for `compare()`, as opposed to returning an int. This would work well with matching, however that doesn't seem to be there yet from what I read in the README.

It would be beneficial to add Comparable to most primitive types as well (Int, String, GUID, ...).

**Comment by mrkmarron** [comment]
Yes, this would be useful. In a previous version there was an [implementation of order comparison](https://github.com/microsoft/BosqueLanguage/blob/7d104275e1375c31a42064db59766a531860ec18/ref_impl/src/interpreter/value.ts#L589) and equality provided for KeyType (and thus Indexable kinds).

This could be moved into the current master. The Indexable type in Core could be modified to provide `equals` and `compare` static methods that surface this operation on their `key` fields.

**Comment by mrkmarron** [comment]
Merging with issue #103
