### ISSUE TITLE
Improve VSCode syntax highlighting

### ISSUE THREAD

**Issue by mrkmarron** [microsoft/BosqueLanguage#19]
The current grammar for syntax highlighting in VSCode is pretty basic. It would be nice to enhance it a bit to be richer and more informative.

**Comment by farleykr** [comment]
Would this be a good issue to use as a base for developing a proper VSCode extension?  If so, I'd love to take on that project if you're game.

**Comment by mrkmarron** [comment]
Hi @farleykr, yes and, in fact, the current highlighting is already setup as a _very_ basic VSCode extension project. The code is in the [bosque-language-tools](https://github.com/Microsoft/BosqueLanguage/tree/master/bosque-language-tools) directory. The first step is probably to improve the highlighting [grammar](https://github.com/Microsoft/BosqueLanguage/blob/master/bosque-language-tools/syntaxes/bosque.tmLanguage.json). 

My initial version was trying to use the TypeScript [highlighting](https://github.com/Microsoft/TypeScript-TmLanguage) as a basis and adjust as we feel looks nice. Would be super happy if you want to take a look and make some improvements.

**Comment by farleykr** [comment]
How should we go about packaging it?  Should it be in its own separate repository?  My thinking is that it would be nice to get it on the VSCode Marketplace as a first step and then go about making improvements from there.

**Comment by mrkmarron** [comment]
Given the early state of the language I don't think we are ready to publish an extension on the VSCode Marketplace. This gives the signal that people can/should start writing applications in the language and that isn't going to go well. 

Until we are a bit further along I would like to keep the tools as part of this repo and a manual installation step (maybe we can build a vsix package though).

**Comment by khoshroomahdi** [comment]
@mrkmarron with publishing vs code extension more people would be familiar to bosque and maybe this repository have more contributers. I think this would be great.

**Comment by khoshroomahdi** [comment]
I think f# syntax highlight is great specifically in nightowl theme. we can copy that.

**Comment by farleykr** [comment]
@khoshroomahdi I believe @mrkmarron said he wanted to try to use TypeScript as a basis for the syntax highlighting so I think that's the direction we're headed.  I'll take a look at F# too and see what inspiration can be taken from it.

**Comment by brakmic** [comment]
Not sure if I should open (yet another) syntax coloring issue, so I hope it's OK to put it here.

------

In this version of VSCode the syntax highlighting isn't working at all:

```shell
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

I'm trying to figure out why. Have executed `npm run compile`, moved the directory to my $HOME/.vscode/extensions, selected Bosque as language for *.bsq files. And still, no syntax coloring. Other options like Compilation don't work either. 

![compiler_error](https://raw.githubusercontent.com/brakmic/bazaar/master/images/random/bosque_compiler_error.png)

**Comment by mrkmarron** [comment]
Hi @brakmic, you are right there was an error in the language highlight regex that was fixed locally but not pushed. That is done now. The compile/test feature is pretty experimental and requires a bit of a confix file (config.json) with the following completely ad-hoc defined format
```
{
    "entrypoint": "NSMain::main",
    "outdir": "bin",
    "app": "calc",
    "files": [
        "ops.bsq"
    ]
}
```

We will need to expand and formalize this when we stabilize the VSCode integration.
