### ISSUE TITLE
Support complex number

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/BosqueLanguage#190]
**What problem would this feature solve? Please describe and, if possible, provide an example.**
I think it is useful for math library
Support complex number like 5j+2

**Comment by deadjdona** [comment]
And quaternions.

**Comment by mrkmarron** [comment]
I would definitely like to make some progress here. The type `Float` is intentionally not defined in the language as I didn't want to privilege a specific format, like IEEE754, over other numeric types. So, ideally we should be able to support rich set of mathematical types and with varying precision in a uniform way.

**Comment by mrkmarron** [comment]
Merging with issue #103
