### ISSUE TITLE
will net core support bosuqe?

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/BosqueLanguage#195]
what is the plan about net core and bosque? is there any chance net core support bosque or not?

**Comment by Richiban** [comment]
I'm pretty sure that many of Bosque's design feature, not least structural typing, make running Bosque on any version of .NET impossible. The CLR simply can't do what Bosque would need it to.

**Comment by mrkmarron** [comment]
Closing with the new AOT compiler landing -- can reopen and revisit once that stabilizes.
