### ISSUE TITLE
better switch statement

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/BosqueLanguage#197]
**What feature do you think could be better?**
switch statement
**Why do you think the current design is unsatisfactory? Please provide a code example if possible.**
always less code to do something is better
**Do you have a proposed alternative design?**
new switch expression in c# 8 is better. the case and return keys should be removed

**Comment by mrkmarron** [comment]
Thanks, do you have a specific example or two where you think the C# version is better than the Bosque version?

**Comment by khoshroomahdi** [comment]
In c# 8 for cases in switch use ex
2=> "two"
But in bosque 
Case 2 => {return "two"}
More bracket and keywords.

**Comment by mrkmarron** [comment]
If you are using the switch as an expression the braces can be omitted.
```
var c = switch(v) {
    case 2 => "two"
    case _ => if(v > 0) "pos" else "neg"
} 
```

The use of "case" is to allow mixing of value patterns "case" and type patterns "type Int => ..." we could probably be clever in the parser and automatically distinguish these but I liked having a bit of visual indication with the "case" and "type" keywords.

**Comment by khoshroomahdi** [comment]
What about case keyword?

**Comment by mrkmarron** [comment]
I think the "case" keyword is still useful for something like:
```
switch(x) {
    type Bool => 0
    type Int => x
    case "yes" => 10
    case "no" => -10
    case _ => 1
}
```

Where the "case" keyword and the "type" keywords explicitly indicate the different matching strategies.

**Comment by khoshroomahdi** [comment]
Yeah, i agree.
@mrkmarron is there any video that include you speak about bosque?
Or do you have any plan stream online and talk more about bosque?

**Comment by mrkmarron** [comment]
Hi @khoshroomahdi I haven't done too much talking about Bosque yet as there are a lot of parts under active development and revision. Hopefully this will start landing later this month and early next. After that, when things should be a bit more stable and usable, I want to start getting more informational material out about the project and language.

**Comment by khoshroomahdi** [comment]
Thanks @mrkmarron. I'm waiting for that.

**Comment by khoshroomahdi** [comment]
Since Int,Bool and other type aee keyword so i think could remove type and case in switch.
