### ISSUE TITLE
Memoization in Bosque?

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/BosqueLanguage#198]
is there memoization in Bosque?

**Comment by mrkmarron** [comment]
Hi, there is not any memoization support in Bosque. However, we are in the process of landing the changes needed to support pragmas and which will allow us to add memoization without adding explicit code:

```
#pragma Cache'{size=512, evict=LRU}'
recursive function fib(n: Int): [Int, Int] {
  return switch(n) {
    case 0 => [0, 0]
    case 1 => [1, 1]
    case _ => [n, fib[recursive](n - 1).1 
                  + fib[recursive](n - 2).1]
  } 
}
```

**Comment by mrkmarron** [comment]
Closing and mentioning issue #37
