### ISSUE TITLE
Parsing issues when runing app_runner

### ISSUE THREAD

**Issue by Gattermeier** [microsoft/BosqueLanguage#199]
Running `node bin/test/app_runner.js FILE.bsq` I would expect the result of the following bsq file to return 6.

```
namespace NSMain;

function nsum(d: Int, ...args: List<Int>): Int {
    return args.sum(default=d);
}

entrypoint function main(): Int {
    return nsum(0, 1, 2, 3);
}
```

Instead, I am running into parsing issues: 
`Parse error -- Expected ";" but found "(" on line ...`  (for `args.sum(default=d);`)

This seems to be true for all methods described in src/core/core.bsq and src/core/collections.bsq. 

Any pointers where I am going wrong here? I had dabled with Bosque a few months prior without running into any issues like these.

**Comment by mrkmarron** [comment]
Hi, it seems there was a mistake in the documentation the `.` operator is for field and property accesses with the `->` operator for method invocations. So changing the call to `args->sum(default=d)` should do the trick.

FYI I am expecting to start merging in some large, breaking, and hopefully very nice updates later this week/early next week.
