### ISSUE TITLE
Different behaviours of require with bcgen+exec vs app_runner

### ISSUE THREAD

**Issue by fstiffo** [microsoft/BosqueLanguage#200]
**Describe the bug**
The `requires` precondition works as expected only with app_runner

**To Reproduce**
My code:
https://gist.github.com/fstiffo/4d2df13c81723132db572343060f925a

**Expected behavior**
Compiling the code with bcgen and executing it with exec should return:
`Done with -- [ 38, 0 ]`
instead it  returns:
`fail with exception -- Error: Pre-Condition Error`

**Desktop (please complete the following information):**
 - OS: W10, node v12.13.1
 - Bosque Version: master downloaded 09.12.19, last commit  b48fe94067dc14c9bd61bfdf1406985ca763f732

**Comment by mrkmarron** [comment]
Recent changes made this a bit out-of-date. I checked the code with the new [AoT compiler](https://github.com/microsoft/BosqueLanguage#executable-generation) and things seem to work as expected. 

Closing for now but please reopen if there are additional issues/questions.
