### ISSUE TITLE
Build conf

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/BosqueLanguage#228]
Hi @mrkmarron. Is there any session about Bosque in build conf?

**Comment by mrkmarron** [comment]
Hi and sorry for the delayed response here. 

We don't have anything scheduled for //build but we did put together a [webinar event](https://note.microsoft.com/MSR-Webinar-Programming-Languages-Bosque-Registration-Live.html?wt.mc_id=twitter_MSR-WBNR_post_v2) with a review of the project, some status updates, and a live Q&A session. I am hoping this will align with the push of the first semi-stable version of the language.

**Comment by khoshroomahdi** [comment]
> Hi and sorry for the delayed response here.
> 
> We don't have anything scheduled for //build but we did put together a [webinar event](https://note.microsoft.com/MSR-Webinar-Programming-Languages-Bosque-Registration-Live.html?wt.mc_id=twitter_MSR-WBNR_post_v2) with a review of the project, some status updates, and a live Q&A session. I am hoping this will align with the push of the first semi-stable version of the language.

Thanks. How do you anounce that webinar? And when would be?

**Comment by mrkmarron** [comment]
The [registration page](https://note.microsoft.com/MSR-Webinar-Programming-Languages-Bosque-Registration-Live.html?wt.mc_id=twitter_MSR-WBNR_post_v2) just went live today. The live event is scheduled for May 14th at 10am PST and there will be a recording for on demand viewing later.
