### ISSUE TITLE
Typed Projection does't consider intersection type as a concept type

### ISSUE THREAD

**Issue by typesAreSpaces** [microsoft/BosqueLanguage#229]
**Describe the bug**
The AOT compiler indicates as a parse error the typed projection of an intersection type object.

**To Reproduce**
Let us consider the following Bosque code:
```
namespace NSMain;

concept Foo {
  field f : Int;
}

concept Bar {
  field f: Int;
}

entity Baz provides Foo, Bar {
  field g: Int;
  field k: Bool;
}

entrypoint function main(): Int {
    
    var e = Baz@{ f=1, g=2, k=true };
    var e2 = e->project<Foo & Bar>();
    
    return 0;
}

```
Let us save this program as main.bsq inside the main directory of the repo (BosqueLanguage). By the following command:
```
node ref_impl/bin/runtimes/exegen/exegen.js -o main main.bsq
```
We observe that the AOT compiler indicates the following:
```
Parse error -- Can only project over record, tuple, or concept contraints on line 19
```

**Expected behavior**
One would expect that the AOT could handle the compilation of the above program.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Bosque Version: Current Master branch (commit 854fa52037b8daef912c1acf1e695e6e1b566636)

**Comment by mrkmarron** [comment]
Should be fixed in master
