### ISSUE TITLE
Can Bosque emulate a Turing machine ?

### ISSUE THREAD

**Issue by philiprbrenan** [microsoft/BosqueLanguage#230]
If it can  then: Bosque can emulate a language that has all the faults that it is designed to suppress   and thus can choose to subvert its design goals. If it cannot: non Turing machines are not universal and thus not very interesting?

**Comment by mrkmarron** [comment]
Technically this is true, you can certainly re-encode and subvert our design goals. For instance you could create a List<Int> and use it to encode raw memory + pointers and malloc. Our goal is not to make these things impossible but to make it easy to write code that avoids these issues.
