### ISSUE TITLE
Not able to execute program in os x

### ISSUE THREAD

**Issue by GariaHarish** [microsoft/BosqueLanguage#231]
I am not able to execute program in os x in mac giving me z3 size file or directory not found   ##sk plz can you suggestion how can I run hello world.

I have done all guideline.

**Comment by mrkmarron** [comment]
Hi @GariaHarish, we are using git lfs to manage the binaries in the repo. It sounds like you need to install lfs `git lfs install` and pull to get the full Z3 binary and not the 0 byte placeholder file.

**Comment by GariaHarish** [comment]
Thanks @mrkmarron
