### ISSUE TITLE
Better documentation...

### ISSUE THREAD

**Issue by lamprosmousselimis** [microsoft/BosqueLanguage#234]
**What feature do you think could be better?**
README.md file must be written carefully...

**Why do you think the current design is unsatisfactory? Please provide a code example if possible.**
function allPositive(...args: List<Int>): Bool {
    return args->allof(fn(x) => x >= 0);
}

allOdd(1, 3, 4) //false

This function returns true iff all numbers are positive. Then you call allOdd function....

Choose one function and stick with it.

**Do you have a proposed alternative design?**

function allPositive(...args: List<Int>): Bool {
    return args->allof(fn(x) => x >= 0);
}

allPositive(1, -3, 4) //false

Or....

function allOdd(...args: List<Int>): Bool {
    return args->allof(fn(x) => x modulo 2 == 1);
}

allOdd(1, 3, 4) //false

**Comment by mrkmarron** [comment]
Thanks fixed now!
