### ISSUE TITLE
Where is the binary located after successful build?

### ISSUE THREAD

**Issue by Tembocs** [microsoft/BosqueLanguage#244]
I've successful built and test Bosque. I trying to look around, can't seem to see the binary executable. Where is it located after building?

**Comment by brakmic** [comment]
If you mean the compiler, it's under `impl/bin/runtimes/exegen`.
You can then use it like this:

```shell

node ./impl/bin/runtimes/exegen/exegen.js --compiler clang++ -o BINARY_NAME YOUR_SOURCE_CODE.bsq
```
