### ISSUE TITLE
[compiler]: error: use of undeclared identifier 'RCReturnFunctor_BSQIdKeyCompound

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#249]
**Describe the bug**

I am trying to compile the following code:

```js
namespace NSMain;

identifier UserId = Int;

entrypoint function main(): UserId {
  let id = UserId@{1};
  return id;
}
```

However, it fails with this error:

```shell
Error -- Error: Command failed: clang++ -g -DBDEBUG -std=c++17 -o ckey /Users/brakmic/projects/BosqueLanguage/impl/bin/scratch/cpp/*.cpp
/Users/brakmic/projects/BosqueLanguage/impl/bin/scratch/cpp/main.cpp:41:5: error: use of undeclared identifier 'RCReturnFunctor_BSQIdKeyCompound'
    RCReturnFunctor_BSQIdKeyCompound{}($$return, $callerscope$);
    ^
1 error generated.
```

I have then tried to fix this error by adding an implementation of **RCReturnFunctor_BSQIdKeyCompound** to **bsqkeyvalues.h**:

```cpp
struct RCReturnFunctor_BSQIdKeyCompound
{
    inline void operator()(BSQIdKeyCompound* idk, BSQRefScope& scope) const 
    { 
        for(size_t i = 0; i < idk->keys.size(); ++i)
        {
            scope.processReturnChecked(idk->keys[i]);
        }
    }
};
``` 

However, the above program now crashes with Segfault 11 (missing some globals, I suppose).

```shell
'./ckey' terminated by signal SIGSEGV (Address boundary error)
```

**To Reproduce**

Compile with `exegen.js --compiler clang++ -o ckey ckey.bsq`

**Expected behavior**

Successful compilation + a meaningful return value.

**Desktop:**
 - OS: macOS Catalina 10.15.4
 - Bosque Version: 0.5.0-rc-1

**Comment by brakmic** [comment]
@mrkmarron 

I ran the above code through **lldb** and here's the place where the error got thrown:

```cpp
(lldb) n
Process 13161 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000100003940 identifiers`BSQ::diagnostic_format(v=0x0000000100205260) at bsqvalue.cpp:242:54
   239              case MIRNominalTypeEnum_Category_Record:
   240                  return DisplayFunctor_BSQRecord{}(*dynamic_cast<BSQRecord*>(vv));
   241              default:
-> 242                  return dynamic_cast<BSQObject*>(vv)->display();
   243          }
   244      }
   245  }
Likely cause: vv accessed 0x0
```

**Comment by brakmic** [comment]
BSQObject's **display** method is pure virtual, if I am not mistaken.

**Comment by mrkmarron** [comment]
I think the root of the problem is that this should create a [BSQIdKeySimple](https://github.com/microsoft/BosqueLanguage/blob/3935da0f6cbabce76773165e6ed81e854164a2fb/impl/src/tooling/aot/runtime/bsqkeyvalues.h#L450) which is handled by value but somewhere code is getting generated to treat it as a Compound key.

**Comment by brakmic** [comment]
There's another thing. The pointer vv seems to be empty:

```cpp
-> 242                  return dynamic_cast<BSQObject*>(vv)->display();
   243          }
   244      }
   245  }
(lldb) p *vv
(BSQ::BSQRef) $3 = (count = 0, nominalType = Invalid)
```

I printed its contents before it tried to cast to BSQObject*.

**Comment by mrkmarron** [comment]
Partial support is incoming. Note that we use special `create` for the indentifiers and will need to add typechecker support:

```
identifier UserId = Int;

entrypoint function main(): UserId {
  let id = UserId::create(1);

  let x = Set<UserId>@{id};
  check x.size() == 1;

  return id;
}

```
