### ISSUE TITLE
List.filter on Int? is always returning List<Int?>

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#265]
**Describe the bug**

Trying to map a filtered `List<Int?>` fails with: 

```shell
Parse error -- ["lists2.bsq",7,"Operand can only be applied to Int, BigInt, or Float64 types"]
```

This is the code:

```js
entrypoint function main(): List<Int> {
  var list: List<Int?> = List<Int?>@{1, 2, none, 3, 4, 5, 6};
  return list.filter(fn(e) => e != none)
             .map<Int>(fn(e) => e * e);
}
```

I have searched a bit through [typechecker.ts](https://github.com/microsoft/BosqueLanguage/blob/master/impl/src/type_checker/type_checker.ts#L2906) and **assembly.ts** and it seems that the function [atomSubtypeOf](https://github.com/microsoft/BosqueLanguage/blob/master/impl/src/ast/assembly.ts#L1821) in **assembly.ts** is always returning a union (NSCore::Int|NSCore::None) which later gets rejected. I have done some primitive debugging and printed out the contents of the two variables **t1** and **t2**:

```shell
[...snip...]
t1: NSCore::Int
t2: NSCore::Any
t1: NSCore::List<NSCore::Int|NSCore::None>
t2: NSCore::List<NSCore::Int|NSCore::None>
t1: NSCore::List<NSCore::Int>
t2: NSCore::List<NSCore::Int>
t1: NSCore::Int|NSCore::None
t2: NSCore::PODType
t1: NSCore::Int|NSCore::None
t2: NSCore::APIType
t1: NSCore::List<NSCore::Int|NSCore::None>
t2: NSCore::List<NSCore::Int|NSCore::None>
t1: NSCore::List<NSCore::Int|NSCore::None>
t2: NSCore::List<NSCore::Int|NSCore::None>
```

When I try an alternative example that has no None, it compiles without errors.

```js
entrypoint function main(): List<Int> {
  var list: List<Int> = List<Int>@{1, 2, 3, 4, 5, 6};
  return list.filter(fn(e) => e > 0)
             .map<Int>(fn(e) => e * e);
}
```

And as expected, the output of **atomSubTypeOf** is different:

```shell
[...snip...]
t1: NSCore::List<NSCore::Int>
t2: NSCore::List<NSCore::Int>
t1: NSCore::List<NSCore::Int>
t2: NSCore::List<NSCore::Int>
t1: NSCore::List<NSCore::Int>
t2: NSCore::List<NSCore::Int>
t1: NSCore::Int
t2: NSCore::PODType
t1: NSCore::Int
t2: NSCore::APIType
```

**Expected behavior**

Filtering a `List<Int?>` with a function that excludes **none** should produce a `List<Int>`.

**Comment by mrkmarron** [comment]
This is a bit funny. In theory we could be clever and do some inference on type changes based on the predicate supplied (sort of a template type inference++) but this requires some careful design about when/how it would refine the type. 

So, for the time being, we use the same conservative approach that TypeScript or C#/LINQ use and provide a specialized `ofType<U>(): List<U>` method (which is a type check and filter) and a `cast<U>(): List<U>` (which is a type cast) for these use cases. Unfortunately, these are not implemented in the C++ bindings yet (but hopefully I'll have some time today to hook up these and  some other stdlib bits).

**Comment by brakmic** [comment]
Great! Then this would work in future:

```js
entrypoint function main(): List<Int> {
  var list: List<Int?> = List<Int?>@{1, 2, none, 4, 5, 6};
  return list.filter(fn(e) => e != none)
             .ofType<Int>()
             .map<Int>(fn(e) => e * e);
}
```

I'm looking forward to working with these new stdlib functions :)

Thanks!

**Comment by mrkmarron** [comment]
Actually it will even be a bit easier since `ofType` will do the filter as well:
```
entrypoint function main(): List<Int> {
  var list: List<Int?> = List<Int?>@{1, 2, none, 4, 5, 6};
  return list
             .ofType<Int>()
             .map<Int>(fn(e) => e * e);
}
```
Also, I really appreciate all the issue/PRs. You are definitely on the bleeding edge of this project but hopefully we should be getting into a much more stable state soon (and your contributions are a big help in this).

**Comment by brakmic** [comment]
> Actually it will even be a bit easier since `ofType` will do the filter as well:
> 
> ```
> entrypoint function main(): List<Int> {
>   var list: List<Int?> = List<Int?>@{1, 2, none, 4, 5, 6};
>   return list
>              .ofType<Int>()
>              .map<Int>(fn(e) => e * e);
> }
> ```

Yes, it's much more elegant!

> 
> Also, I really appreciate all the issue/PRs. You are definitely on the bleeding edge of this project but hopefully we should be getting into a much more stable state soon (and your contributions are a big help in this).

I'm glad I could help. :)

I'm trying to understand the C++ code as well, but this would need more time. Have just looked into `static BSQList<U, U_RCDecF, U_DisplayF>* list_oftype(Ty* l)` but couldn't figure out how to forward the needed variables and type information in `cppbody_emitters.ts`. There are many similarities between functions in `generateBuiltinBody`, but the subtle differences and my lack of deeper knowledge are (for now) stopping me from doing more. 

Btw. I have registered https://bosque-lang.org and uploaded some rudimentary design and linked a few resources there. Maybe one day it can serve the project. I can also hand over the ownership of the site, if needed.

**Comment by mrkmarron** [comment]
I like the looks of the website and we can revisit how to best handle the domain in a few months when we are ready to bring a wider range of users into the language.

**Comment by brakmic** [comment]
Here's the repo of the website: https://github.com/brakmic/bosque-lang.org
It's based on jekyll so GitHub does all the rendering for us, so I don't have to deal much with CSS :)
