### ISSUE TITLE
It should be possible to pass custom flags to the compiler

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#267]
**What problem would this feature solve? Please describe and, if possible, provide an example.**

On my macOS Catalina 10.15.4 I often use **g++-9** instead of **clang++**, but since yesterday I am running into weird problems regarding a missing include from TBB library:

```shell
In file included from /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/pstl/parallel_backend.h:14,
                 from /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/pstl/algorithm_impl.h:25,
                 from /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/pstl/glue_execution_defs.h:52,
                 from /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/execution:32,
                 from /Users/brakmic/projects/BosqueLanguage/impl/bin/scratch/cpp/bsqcustom/bsqlist_ops.h:7,
                 from /Users/brakmic/projects/BosqueLanguage/impl/bin/scratch/cpp/bsqruntime.h:11,
                 from /Users/brakmic/projects/BosqueLanguage/impl/bin/scratch/cpp/main.cpp:1:
/usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/pstl/parallel_backend_tbb.h:19:10: fatal error: tbb/blocked_range.h: No such file or directory
   19 | #include <tbb/blocked_range.h>
```

Now, one could say: *just use clang++*, but I think that we should be able to pass *compiler flags* in general. My first reaction to the error above was to try to include the needed include and lib paths, but as there is no way to pass those via *exegen.js* my only "solution" was to go back to clang++.

**Do you have a proposed solution? If so please share it.**

Yes, I will open a new PR that introduces a new option **-f --flags** which can be used to pass compiler flags. 

Example:

```shell
exegen.js --compiler g++-9 --flags "-I/usr/local/opt/tbb/include -L/usr/local/opt/tbb/lib -ltbb" --level debug -o exefile source.bsq
```

**Comment by mrkmarron** [comment]
The PR looks good and is a nice additional feature so I'll merge it shortly.

I believe the change that happened involved the intro of the header `#include <execution>` which provides `std::execution::par_unseq`. This is nifty for parallelizing some execution but, since we will later care about bin size and memory footprint, may not be worth it in the long term.

**Comment by brakmic** [comment]
Yes, I encountered that error too, but only when using GCC v8.
