### ISSUE TITLE
Code with Set<T> doesn't compile when T is a user-defined type

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#269]
**Describe the bug**

This code fails to compile with: 

```shell
Parse error -- ["sets.bsq",11,"Template instantiation does not satisfy specified bounds"]
```

```js
namespace NSMain;

entity Person {
  field name: String;
}

entrypoint function main(): Bool {
  let person = Person@{"john"};
  let person2 = Person@{"jakob"};
  let person3 = Person@{"marcus"};
  let users = Set<Person>@{person, person2, person3};
  return users.has(person2);
}
```

It seems that in _type_checker's_ function **checkTemplateTypes** there is a problem [with determining the subtype](https://github.com/microsoft/BosqueLanguage/blob/master/impl/src/type_checker/type_checker.ts#L147).

**Comment by brakmic** [comment]
When I try the same with Set<Int> it works and also the behavior of the function [normalizeType_Nominal](https://github.com/microsoft/BosqueLanguage/blob/3935da0f6cbabce76773165e6ed81e854164a2fb/impl/src/ast/assembly.ts#L822) in assembly.ts is different. Here the console.log output of **t: NominalTypeSignature** variable when done with `Set<Person>`

```shell
{
[...snip...]
  {
   "nameSpace": "NSCore",
   "baseName": "Set",
   "terms": [
      {
         "nameSpace": "NSMain",
         "baseName": "Person",
         "terms": []
      }
   ]
}
[...snip...]
```

And here when using Set<Int>:

```shell
[...snip...]
{
   "nameSpace": "NSCore",
   "baseName": "Set",
   "terms": [
      {
         "nameSpace": "NSCore",
         "baseName": "Int",
         "terms": []
      }
   ]
}
{
   "nameSpace": "NSCore",
   "baseName": "Expandoable",
   "terms": [
      {
         "name": "T"
      }
   ]
}
{
   "nameSpace": "NSCore",
   "baseName": "Expandoable",
   "terms": [
      {
         "name": "T"
      }
   ]
}
[...snip...]
```

I have omitted all other "empty" entries.

**Comment by mrkmarron** [comment]
Hi, this is a novel aspect of Bosque. We restrict the types that can be used in Sets and as Keys for Maps to `KeyType` types. This does not allow user defined types like the Person in your example and why there is special support for creating custom identifier keys (which are currently buggy #249).

**Comment by brakmic** [comment]
> Hi, this is a novel aspect of Bosque. We restrict the types that can be used in Sets and as Keys for Maps to `KeyType` types. This does not allow user defined types like the Person in your example and why there is special support for creating custom identifier keys (which are currently buggy #249).

Thanks for the explanation.

I actually started with a Person entity that container an identifier like this:

```js
identifier UserKey = {id: Int, type: String};

entity Person {
  field id: UserKey;
  field name: String;
}
```

But because I encountered the above error, I thought it might have to do something with it and removed it.

**Comment by mrkmarron** [comment]
Yes, the that is one issue. It also makes it possible to have 2 different objects with the same key floating around and then there need to be lots of explicit rules about (say when adding to a set) which one wins.
