### ISSUE TITLE
Set.has(IdKey) always returns false for compound identifiers

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#275]
**Describe the bug**

When working with compound keys `Set.has(IdKey)` always returns `false`.

```js
namespace NSMain;

identifier UserKey = {id: Int, typ: String };

entrypoint function main(): Bool {
  let id = UserKey::create(1, "staff");
  let id2 = UserKey::create(2, "staff");
  let id3 = UserKey::create(3, "staff");
  let ids = Set<UserKey>@{id, id2, id3};
  return ids.has(id2);
}
```

```shell
./sets 
false
```

When I use simple identifiers the behavior is different:

```js
namespace NSMain;

identifier UserId = Int;

entrypoint function main(): Bool {
  let id = UserId::create(1);
  let id2 = UserId::create(2);
  let id3 = UserId::create(3);
  let ids = Set<UserId>@{id, id2, id3};
  return ids.has(id2);
}
```

```shell
./sets
true
```

**To Reproduce**

Compile with `exegen.js -c clang++ -o sets sets.bsq`.

**Expected behavior**
A `true` should be returned if Set<IdType> contains the given compound identifier.

**Comment by brakmic** [comment]
I have changed `LessFunctor_int64_t` to print out values it was comparing and this is what it looked like for `Set<UserKey>`:

```shell
l: 2, r: 1
l: 3, r: 2
l: 2, r: 1
l: 1, r: 2
```

With `Set<UserId>` it looked like this:

```shell
l: 2, r: 1
l: 3, r: 2
l: 2, r: 2
l: 1, r: 2
l: 2, r: 2
```

There's one comparison more when checking simple identifiers.

**Comment by mrkmarron** [comment]
Merging a PR to fix this. The following should now work as expected:
```

identifier UserKey = { id: Int, category: String };

entrypoint function main(): Bool {
  let id = UserKey::create({id=1, category="staff"});
  let id2 = UserKey::create({id=2, category="staff"});
  let id3 = UserKey::create({id=3, category="staff"});
  let ids = Set<UserKey>@{id, id2, id3};

  return ids.has(id2);
}

```

**Comment by brakmic** [comment]
Great!
Should I close my PR https://github.com/microsoft/BosqueLanguage/pull/274 ?

**Comment by mrkmarron** [comment]
Yeah that would be great. Thanks.
