### ISSUE TITLE
Switch with matching on type doesn't compile

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#298]
**Describe the bug**

This code from [language docs](https://github.com/microsoft/BosqueLanguage/blob/master/docs/language/overview.md#68-switch) doesn't compile:

```js
namespace NSMain;

entrypoint function main(): Any {
  let x = 1;
  switch(x) {
    type Bool => { return false; }
    type Int => { return 0; }
    type String => { return ""; }
    type {f: Int, g?: Bool} => { return x.f; }
    case _ => { return none; }
  }
}
```

```shell
Error -- TypeError: Cannot read property 'resultType' of undefined
```

**Comment by mrkmarron** [comment]
It looks like this has the same thing going on as #286 where they type checker infers that the `type Int` clause is always true and then doesn't handle the remaining cases cleanly. 

In addition to fixing this in general for control flow actions a big todo item is going to be updating the language docs and adding all the examples in there to the unit tests.

**Comment by brakmic** [comment]
> It looks like this has the same thing going on as #286 where they type checker infers that the `type Int` clause is always true and then doesn't handle the remaining cases cleanly.
> 
> In addition to fixing this in general for control flow actions a big todo item is going to be updating the language docs and adding all the examples in there to the unit tests.

Many thanks for the explanation. As I am still writing the 2nd part of my Bosque article I keep on finding such errors. Will then simply avoid this switch-example and use all others that compile. :)

**Comment by brakmic** [comment]
The example with [yield](https://github.com/microsoft/BosqueLanguage/blob/master/docs/language/overview.md#65-return-and-yield) seems to be affected by the same problem as well.

```js
namespace NSMain;

function abs(x?: Int): Int {
    if(x == none) {
        return 0;
    }

    return {
        var y = x;
        if(y < 0) {
            y = -y;
        }
        yield y;
    }
}

entrypoint function main(): Int {
  return abs(-123);
}
```

Compilation fails with: 

```shell
Parse error -- ["yield.bsq",9,"Expected \"(\" but found \"var\""]
Parse error -- ["yield.bsq",15,"Expected \";\" but found \"}\""]
```

**Comment by mrkmarron** [comment]
That one looks like some simple syntax changes so the following should work:
```
function abs(x?: Int): Int {
    if(x == none) {
        return 0;
    }

    return {|
        var y = x;
        if(y < 0) {
            y = -y;
        }
        yield y;
    |};
}
```

**Comment by brakmic** [comment]
> That one looks like some simple syntax changes so the following should work:
> 
> ```
> function abs(x?: Int): Int {
>     if(x == none) {
>         return 0;
>     }
> 
>     return {|
>         var y = x;
>         if(y < 0) {
>             y = -y;
>         }
>         yield y;
>     |};
> }
> ```

Many thanks. Will check it and maybe I should also update the docs. :)

**Comment by mrkmarron** [comment]
Also, I am very curious if you have been trying any `symtest` examples and what your take on that has been?

**Comment by brakmic** [comment]
> Also, I am very curious if you have been trying any `symtest` examples and what your take on that has been?

Yes, I have executed `npm run test` a few times. I've also thought about expanding tests, for example when I was working on List.sort, but I wasn't sure if this is a good idea as the language is expanding very quickly. 

I'd like to add more specific tests, like trying out various static functions with *.sort, *.filter etc. 

Also, it'd be of advantage to test for "correct" error messages by deliberately provoking errors. I'm not sure if there are such tests already, but it'd be nice to know that a function would return a human-readable message so we can later locate the culprit more easily.

Maybe also thinking about adding a true test framework, something like Mocha/Jasmine/Karma.
