### ISSUE TITLE
GC design

### ISSUE THREAD

**Issue by mrkmarron** [microsoft/BosqueLanguage#30]
The fact that Bosque does not have reference identity opens up some interesting GC opportunities. 

For example one could potentially do something like racy parallel copies for collection which may result in some pointers to the old version and some to the new copy. This would be ok as it does not impact the semantics of the program and, if it is infrequent, should not impact perf/fragementation much until it is repaired next collection.

I am personally very intersted in the possbility of implementing an RC based system (potentially with unique type support - issue #28) to favor performance predictability over max throughput.

**Comment by orcmid** [comment]
Hmm, yes with immutability, RC based operation seems very attractive.  I'm not so clear about performance predictability.  

I have been thinking that the performance price of a construction needs to also bear the cost of eventual destruction.  But amortization in actual operation needs to be considered.  There can be spasmodic clumping unless one finds a way to defer cleanups to idle-/blocked times, and one blocking case may be when it is necessary recover some free space from unreachable but not-cleaned-up space.  It would also be great for rapid cleanup of ephemeral objects in an easily-handled working set case that can be handled off any heap.

Is there any thinking on how some sort of generational recognition might help, even with RC as the main scheme?

**Comment by B-Teague** [comment]
This is probably worth reading:
https://yager.io/programming/go.html

**Comment by mrkmarron** [comment]
Novel RefCount GC landing in master.
