### ISSUE TITLE
Map's values() method returns a wrong type

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#302]
**Describe the bug**

While I was trying to compile this code I encountered a "type error" that made me searching for a solution. *Then I stumbled upon another problem*.

```js
namespace NSMain;

entrypoint function main(): List<String> {
  let map = Map<Int, String>@{[1, "value1"], [2, "value2"]};
  let names = map.values();
  return names;
}
```

I don't know why, but the compiler always returns `Parse error -- ["maps2.bsq",4,"Type error"]`

However, if I define an empty map I get this error instead: 

`Error -- AssertionError [ERR_ASSERTION]: Need to implement -- NSCore::Map::s_values`

Obviously, a `maps_values` entry in `cppbody_emitter.ts` is missing. This would be a separate problem to solve, but what's interesting are method signatures in `map.bsq` sources from `cpp` & `symbolic` which looked like this:

```js
    method values(): List<K> {
        return Map<K, V>::s_values(this);
    }
```

I think that the **List type** is wrong, because values are returned, not keys. 

*But I still don't know why I can't instantiate a map with some KeyValue entries in them?*

**Comment by mrkmarron** [comment]
Maps are now created using `MapEntry` types which have a special shorthand constructor syntax `K => V`. An example from the tests is:
```
entrypoint function main(): Int {
    let l = List<Int>@{1, 2, 3};
    let m = Map<Int, Bool>@{1 => true, 2 => true, 3 => false};

    let ll = l.projectWithMap<Bool>(m);
    check ll.size() == 3;
    check ll.front() == true;
    check ll.back() == false;

    return 0;
}
```
Also, FYI, maps are probably pretty buggy right now. I was hoping to get to writing tests for them and fixing things up sometime this week. Feel free to try things out/open issues but be prepared.
