### ISSUE TITLE
WASM compilation

### ISSUE THREAD

**Issue by mrkmarron** [microsoft/BosqueLanguage#31]
Currently we have a simple (and poor performance) interpreter reference implementation. Having a WASM compiler target and runtime. This will also require some GC design (see issue #30) but it might be ok to start with a simple RC based design.

**Comment by wandyezj** [comment]
Is it possible for Bosque programs to be a stricter set of existing TypeScript programs with additional libraries and for Bosque to translate to TypeScript? That way all the existing resources for TypeScript could be recycled, and libraries developed in Bosque could be easily consumed by existing TypeScript programs.

It would be nice to have strictly verified libraries for core functionality with looser rules for less core components in a program or website.

**Comment by mrkmarron** [comment]
AOT compiler landing in master -- revisit this soon.
