### ISSUE TITLE
Is there pipe and range operator in bosque? 

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/BosqueLanguage#314]
Is there pipe and range operator in bosque? If yes how is the syntax? If no, is there any plan for them?

**Comment by khoshroomahdi** [comment]
Range operator in f sharp
[1..2..100]
[1..50]

**Comment by mrkmarron** [comment]
PR #319 includes the implementation of a ListOf::range(start, end) method that generates a list of ints in the range [start, end). Which, adds this functionality, although without a special syntax.
