### ISSUE TITLE
Implement synthesis blocks

### ISSUE THREAD

**Issue by mrkmarron** [microsoft/BosqueLanguage#32]
Inspired by this [paper](https://mehrdad.afshari.me/publications/prorogued-programming/paper.pdf) I would like to implement synthesis blocks as a first class language feature (and a synthesis engine to support it). 

Several questions are what can a programmer specify for the block, types, pre/post, examples, etc. and what is the synthesis methodology.

**Comment by claytonsingh** [comment]
Looks like the link to that paper is dead.

**Comment by mrkmarron** [comment]
Yep, link is dead. This paper "Liberating the Programmer with Prorogued Programming" should also be available [here](http://earlbarr.com/publications/prorogue.pdf).
