### ISSUE TITLE
Math operations fail with 'bad type signature error'

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#344]
**Describe the bug**
Trying to compile the following code fails with a `Bad type signature` error.

```js
namespace NSMain;

entrypoint function main(): Int {
    return NSMain::Math::div(NSMain::Math::mult(10, 9), 10);
}
```

I also had to use the full namespaces, because **Math::div** and **Math::mult** alone were leading to another error: `Could not resolve namespace`.

**Comment by mrkmarron** [comment]
mult and div are now available as the infix operators *, /

so the example can be rewritten as below and should work:
```
namespace NSMain;

entrypoint function main(): Int {
    return (10 * 9) / 10;
}
```
