### ISSUE TITLE
entrypoint function doesn't accept List<T> and other (more complex?) types

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#348]
**Describe the bug**
Trying to compile this code results in a type conversion error:

```js
namespace NSMain;

entrypoint function main(numbers: List<Int>): List<Int> {
    return numbers;
}
```

```shell
Error -- Error: Command failed: clang++  -g -DBDEBUG -std=c++17 -o input /workspaces/BosqueLanguage/impl/bin/scratch/cpp/*.cpp
/workspaces/BosqueLanguage/impl/bin/scratch/cpp/main.cpp:61:44: error: no matching function for call to 'nsmain__mainI33I'
    std::cout << diagnostic_format(((Value)nsmain__mainI33I(numbers, _scope_I35I))) << "\n";
                                           ^~~~~~~~~~~~~~~~
/workspaces/BosqueLanguage/impl/bin/scratch/cpp/main.cpp:33:34: note: candidate function not viable: no known conversion from 'BSQ::BSQString' to 'BSQ::nscore__list_t_nscore__int_I10I *' for 1st argument
nscore__list_t_nscore__int_I10I* nsmain__mainI33I(nscore__list_t_nscore__int_I10I* numbersI32I, BSQRefScope& $callerscope$)
```

I have also tried some experiments, just to see how the compiler would react.

For example this:

```js
namespace NSMain;

entrypoint function main(numbers: Any): Any {
    return numbers;
}
```

The error was: `Only APIValue types are supported as inputs of Bosque programs.`

I have then tried to construct such a type:

```js
namespace NSMain;

entity InputValue provides APIType {
    
}

entrypoint function main(numbers: InputValue): InputValue {
    return numbers;
}
```

However, the same conversion error appeared again:

```shell
Error -- Error: Command failed: clang++  -g -DBDEBUG -std=c++17 -o input /workspaces/BosqueLanguage/impl/bin/scratch/cpp/*.cpp
/workspaces/BosqueLanguage/impl/bin/scratch/cpp/main.cpp:70:44: error: no matching function for call to 'nsmain__mainI33I'
    std::cout << diagnostic_format(((Value)nsmain__mainI33I(numbers, _scope_I16I))) << "\n";
                                           ^~~~~~~~~~~~~~~~
/workspaces/BosqueLanguage/impl/bin/scratch/cpp/main.cpp:42:25: note: candidate function not viable: no known conversion from 'BSQ::BSQString' to 'BSQ::nsmain__inputvalueI15I *' for 1st argument
nsmain__inputvalueI15I* nsmain__mainI33I(nsmain__inputvalueI15I* numbersI32I, BSQRefScope& $callerscope$)
```

I have tried to find a solution in the docs on APITypes, but there isn't much that I could deduce from it.

Maybe it's simply because it isn't finished yet?

**Comment by mrkmarron** [comment]
Yeah, this is not finished yet. I was supposed to be implementing the API type parsing and serialization code but I got pulled into some GC related work. Right now the `main` function only works with a small set of primitives, Bool, Int, String.

**Comment by brakmic** [comment]
Ok, no problem. 

The reason behind this issue and https://github.com/microsoft/BosqueLanguage/issues/349 is that I am trying to implement a small neural network example. There are gazillions of examples in Python, so I thought it could be done in Bosque as well. 

Basically, there would be two small programs. One would generate and return an array matrix with lots of float values. These would constitute the "training examples". This data would then become the "input" of another program to train a network. 

Of course, it doesn't need to be it that way as I could simply make such a matrix part of a single program, but I thought it'd be a nice example if there was a way to combine two programs via piping.

`generate_matrix | train_network`

But as you already helped me [regarding casting](https://github.com/microsoft/BosqueLanguage/pull/350) I can now concentrate on the example itself. The piping can wait. :)

Thanks a lot!

**Comment by mrkmarron** [comment]
That sounds like a great example and I am very interested to see it. Just FYI I suspect the performance is going to be pretty bad due to the GC issue and some key optimizations currently missing but it would be great to have this sort of workload as a performance benchmark to improve on.

There may be some other Float64 functions that you need that are missing (or have some bugs). If you run into anything please open an issue and I will try to get to it ASAP.
