### ISSUE TITLE
List<T>.cast<U> doesn't work. 

### ISSUE THREAD

**Issue by brakmic** [microsoft/BosqueLanguage#349]
**Describe the bug**
Compiling this code leads to an error regarding "lambda capture list".

This, however, doesn't seem to be the actual error as C++ compiler assumes that the generated **[object Object]** is a lambda capture list.

```js
namespace NSMain;

entrypoint function main(): List<Float64> {
    let inputs = List<Int>@{2, 5, 7, 3, 9};
    return inputs.cast<Float64>();
}
```

```shell
Error -- Error: Command failed: clang++  -g -DBDEBUG -std=c++17 -o neuralnet /workspaces/BosqueLanguage/impl/bin/scratch/cpp/*.cpp
/workspaces/BosqueLanguage/impl/bin/scratch/cpp/main.cpp:46:194: error: expected ',' or ']' in lambda capture list
    if(lI34I->entries.size() != 0) { BSQ_ABORT("Invalic element to cast", "/workspaces/BosqueLanguage/impl/bin/core/cpp/list.bsq", 43); } auto $$return = BSQ_NEW_ADD_SCOPE(_scope_I36I, [object Object], MIRNominalTypeEnum::nscore__list_t_nscore__float64_I10I);
                                                                                                                                                                                                 ^
1 error generated.
```

I have followed the compilation a bit and it seems that `generateTypeCheck` in cppbody_emitter.ts can't work with given `ctype`.

`const codetc = this.generateTypeCheck("v", ctype, ctype, rlctype);`

But the `idecl`, `ctype` and `ltype` variables contain the needed information for type construction, I think.

This is how their JSON representations look like.

```shell
{
   "enclosingDecl": "NSCore::List<T=NSCore::Int>",
   "name": "s_cast",
   "iname": "NSCore::List::s_cast",
   "key": "NSCore::List::s_cast<T=NSCore::Int, U=NSCore::Float64>",
   "sourceLocation": {
      "line": 43,
      "column": 0,
      "pos": 2831,
      "span": 6
   },
   "srcFile": "/workspaces/BosqueLanguage/impl/bin/core/cpp/list.bsq",
   "attributes": [
      "hidden",
      "recursive?"
   ],
   "recursive": false,
   "pragmas": [],
   "params": [
      {
         "name": "l",
         "type": "NSCore::List<T=NSCore::Int>"
      }
   ],
   "resultType": "NSCore::List<T=NSCore::Float64>",
   "implkey": "list_cast",
   "binds": {},
   "pcodes": {}
}
{
   "trkey": "NSCore::List<T=NSCore::Int>",
   "options": [
      {
         "trkey": "NSCore::List<T=NSCore::Int>",
         "ekey": "NSCore::List<T=NSCore::Int>"
      }
   ]
}
{
   "trkey": "NSCore::Int",
   "options": [
      {
         "trkey": "NSCore::Int",
         "ekey": "NSCore::Int"
      }
   ]
}
```

**Comment by mrkmarron** [comment]
There isn't an path for implicit conversion from Int to Float64, so this should be an error (instead you would need to explicitly convert).

That said it should report there error instead of triggering a C++ compiler error.

**Comment by brakmic** [comment]
I have unsuccessfully tried various options to convert from Int to Float64.
It seems there is no static method "cast" or anything similar to it. 

Have also tried `Float64@{value}` and `Float64::cast(value)`. But there seems to be no way to do casting via constructor or static methods.

Have also tried `list.map<Float64>(fn(e) => ???)` but I am not sure what should go there. Have tried various things.

So far, no doc entries on casting and the only casting examples from *tests* are related to List::cast<Int>.
A bit counter-intuitive that List::cast<Int> works while other cast types don't.

If I only knew more about it I'd write a few lines in the docs.

**Comment by mrkmarron** [comment]
Yeah, the FP support is not as fully/cleanly integrated as I would like yet. I am just about to close a PR that should fix this issue by  providing a `toFloat64` method for ints (and also `toInt`). So you should be able to do `l.map<Float64>(fn(x) => x.toFloat64())`.
