### ISSUE TITLE
Not able to execute mod(%)

### ISSUE THREAD

**Issue by GariaHarish** [microsoft/BosqueLanguage#351]
**I am trying to get odd and even number**
namespace NSMain;
entrypoint function main(arg: Int): String{
    var checkNumber = arg%2;
    if(checkNumber == 0){
        return "Even Number";
    }
    else{
        return "Odd Number";
    }
}

Getting Parse error -- ["./myBsqProj/main.bsq",3,"Expected \";\" but found \"[ERROR]\""].

Are you supporting % mod or I see there is Math::mod(arg, 2);  
but that also asking "Could not resolve namespace"]

Could you help please.

**Comment by mrkmarron** [comment]
Hi, Bosque doesn't use `%` as a symbolic mod operator. Instead `mod` is provided as a static method on the `Int` type definition. So the following compiles and works as expected:
```
entrypoint function main(arg: Int): String{
   var checkNumber = Int::mod(arg, 2);
   
   if(checkNumber == 0){
      return "Even Number";
   }
   else{
      return "Odd Number";
   }
}
```

**Comment by GariaHarish** [comment]
Thanks @mrkmarron for reply.
but if its static method of Int why still giving Error -- AssertionError [ERR_ASSERTION]: Need to implement -- NSCore::Int::mod

**Comment by mrkmarron** [comment]
Hmm, I was able to compile and run this on the master branch. 

Are you compiling this with `exegen` or trying to run `symtest`?

**Comment by GariaHarish** [comment]
I compiled and run using both `exegen` and `symtest`(OS X). also I have latest pull.

**Comment by mrkmarron** [comment]
Ok, `mod` was not implemented in the symbolic execution runtime but PR #352 fixes this. After this is merged you should be able to take the following code and both compile and test it. The tester will report a possible error (you can uncomment the requires line and then it will report that no errors could be found). The compiler should work and produce the expected results as well.

```
entrypoint function main(arg: Int): String 
   //requires arg >= 0;
{
   var checkNumber = Int::mod(arg, 2);
   
   if(checkNumber == 0){
      return "Even Number";
   }
   else{
      return "Odd Number";
   }
}
```

Thanks and please re-open this issue you are still seeing any problems.
