### ISSUE TITLE
Cannot read property 'resultType' of undefined while compiling any Bosque program

### ISSUE THREAD

**Issue by Ivo-Balbaert** [microsoft/BosqueLanguage#353]
**Describe the bug**
Running of any Bosque program returns the same error:

**To Reproduce**

E:\Bosque\examples>node C:\BosqueLanguage\impl\bin\test\runner.js hello.bsq
C:\BosqueLanguage\impl\bin\tooling\aot\cppdecls_emitter.js:224
        const restype = typeemitter.getMIRType(entrypoint.resultType);
                                                          ^

TypeError: Cannot read property 'resultType' of undefined
    at Function.emit (C:\BosqueLanguage\impl\bin\tooling\aot\cppdecls_emitter.js:224:59)
    at Immediate.<anonymous> (C:\BosqueLanguage\impl\bin\test\runner.js:101:55)
[90m    at processImmediate (internal/timers.js:458:21)[39m

with hello.bsq:

namespace NSMain;

entrypoint function main(): String {  
    return "Hello World - Welcome to Bosque programming!";  
}  

Any bsq source file gives the same compiler error, for example same for readme.bsq, tictactoe.bsq, etc.

**Expected behavior**
Output  "Hello World - Welcome to Bosque programming!" to standard output.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10.0.18363  64 bit
 - Bosque Version: downloaded from GitHub Jul 27

Node v 14.6.0
npm  v3.10.9
typescript@3.9.7
Clang 10.0.0 from LLVM 10

**Additional context**
I ran into a problem with npm, so I installed Node 14.6.0 instead of the LTS version; this was perhaps not necessary.

Bosque itself was installed successfully and all tests passed:
All 6 test suites passed!

I am very new to Bosque, so I apologize if this is a no-brainer. Perhaps this is not the right command to run a bsq program, but I couldn't find a docs section on running programs. Thanks for any help.

**Comment by mrkmarron** [comment]
Hi, the `test\runner.js` code is intended only for running the unit tests. So, it is not going to be very user-friendly. Instead I would recommend using the `.\bin\runtimes\exegen\exegen.js` cmd line tools for building .exe files and the `.\bin\runtimes\symtest\symtest.js` for running the sumbolic tester.

The results I have running your same (on the latest version of master) are show below. This should clear things up other wise we can investigate more.

Running your application with these I get the following:
```
C:\Code\BosqueQuick\impl> node .\bin\runtimes\exegen\exegen.js hello.bsq
Compiling Bosque sources in files:
hello.bsq
...
Transpiling Bosque assembly to C++ with entrypoint of NSMain::main...
Writting C++ files...
Compiling C++ code with clang.exe  -g -DBDEBUG -std=c++17 into exe file "a.exe"...
Done with executable -- a.exe
PS C:\Code\Bosque\impl> .\a.exe
"Hello World - Welcome to Bosque programming!"
```

and for the symbolic test tool:
```
PS C:\Code\Bosque\impl> node .\bin\runtimes\symtest\symtest.js hello.bsq
Symbolic testing of Bosque sources in files:
hello.bsq
...
Transpiling Bosque assembly to bytecode with entrypoint of NSMain::main...
Running z3 on SMT encoding...
Verified up to bound -- no errors found!
```

**Comment by Ivo-Balbaert** [comment]
This works perfectly!
Thanks for such a prompt answer. Continuing my Bosque journey...
