### ISSUE TITLE
Parse error in frontpage example Pre/Post Conditions

### ISSUE THREAD

**Issue by Ivo-Balbaert** [microsoft/BosqueLanguage#354]
**Describe the bug**
The Pre/Post Conditions example does not compile for me.

**To Reproduce**
node C:\BosqueLanguage\impl\bin\runtimes\exegen\exegen.js pre_post.bsq
Compiling Bosque sources in files:
pre_post.bsq
...
Parse error -- ["pre_post.bsq",41,"Expected \"(\" but found \"::\""]
Parse error -- ["pre_post.bsq",41,"Expected \")\" but found \";\""]

Line 41 is the following line in function getSays:

return String::concat("The ", animal, " says ", createAnimal::(catchPhrase).says);

**Expected behavior**
Parsing ok and producing an a  executable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bosque Version :  master, installed Jul 27

**Comment by mrkmarron** [comment]
Hi, yes there was a bad typo there. I have updated the code with the correct line of:
```
return ok(String::concat("The ", animal, " says ", createAnimal(catchPhrase).says));
```

Thanks

**Comment by Ivo-Balbaert** [comment]
Thanks, this works!
