### ISSUE TITLE
Switch when example from language doc doesn't compile.

### ISSUE THREAD

**Issue by Ivo-Balbaert** [microsoft/BosqueLanguage#356]
**Describe the bug**
The switch when code snippet described in the Language Docs § 6.8 does not compile.

**To Reproduce**

namespace NSMain;

entrypoint function main(): Any {
    let x = 10;
    switch(x) {
        case Int when x >= 0 => { return x; }
        case Int when x < 0  => { return -x; }
        case {f=_: Int, g=let y: Int} when y != 0 => { return y; }
        case _ => { return -1; }
    }
}

This does not compile and gives the error:
         Parse error -- ["switch_when.bsq",5,"Unknown token sequence in parsing expression"]
on the line:  switch(x) {

**Expected behavior**
10 should be shown as return value

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Bosque Version:  installed from master Jul 27

**Comment by mrkmarron** [comment]
Thanks, I will look into this.
