### ISSUE TITLE
Is there a doc on the intermediate representation

### ISSUE THREAD

**Issue by dibyendumajumdar** [microsoft/BosqueLanguage#357]
I was hoping to see a description of the IR given that is a key feature.

**Comment by mrkmarron** [comment]
Yes this is definitely something that needs to happen. Thanks for opening the issue.

**Comment by dibyendumajumdar** [comment]
Very interested to see what the IR is like and what differentiates it from other IRs, i.e. makes it analyzable. Understand why all the docs refer to the language implementation (I guess that is more appealing to users) - but unless I am mistaken, a different language could target the same IR and get all the benefits, am I right?
