### ISSUE TITLE
What are these branches for?

### ISSUE THREAD

**Issue by catchmareck** [microsoft/BosqueLanguage#359]
I can see three branches in this repository:

- `master`
- `bmc_preview`
- `v1`

What are they used for? I can see that `master` differs *a lot* from the other two. Is it the latest version? Which version should be used to test and play with Bosque - the one on `master` or maybe the one on the `v1` branch?

**Comment by mrkmarron** [comment]
Right now we are doing everything relevant directly in `master` so that is the one you should use to try things out in. 

The project is currently pre-1.0 and I expect things to continue to change for a bit longer.
