### ISSUE TITLE
Provided z3 binary for windows is 32 bit instead of 64 bit

### ISSUE THREAD

**Issue by RaniSharim** [microsoft/BosqueLanguage#360]
When trying to use it on a windows 64 platform, npm test fails because the z3 version is incompatible.
Replacing the z3 version with one of the new 64 bit releases seem to work fine.

**Comment by mrkmarron** [comment]
Hi, Z3 is included in the repo via git-lfs. If this isn't run (see below) the binary size will be zero. I am suspicious this is the cause of the problem. Do you happen to recall if you ran lfs?
```
git lfs install 
```

**Comment by RaniSharim** [comment]
Yes, that seems to be it.
Thank you!
