### ISSUE TITLE
What about multiple files support?

### ISSUE THREAD

**Issue by joelibaceta** [microsoft/BosqueLanguage#361]
I'm planing to write an small lib but as far as I now Bosque doesn't support multiple files scripting or "`Import`" syntax yet right?, I think it would be very useful in order to build more complex tools as micro frameworks

**Comment by mrkmarron** [comment]
Hi @joelibaceta, sorry for the delay in following up. There is syntax support for importing and exporting symbols from code in different files but, you are correct, that the current compiler does not support loading multiple files. There is a substantial chunk of work going on in the code gen part of the project right now but once that is merged the plan is to focus on these types of usability items. 

The story is similar for issue #364 that you have opened.

**Comment by joelibaceta** [comment]
@mrkmarron sure no problem, thanks for reply, I'll keep waiting for the usability features.
