### ISSUE TITLE
Postcondition `ensures` does not compile when ref parameter provided

### ISSUE THREAD

**Issue by catchmareck** [microsoft/BosqueLanguage#378]
**Describe the bug**
When I add a `ref` parameter to a function I can't use the `ensures` check because unhandled errors appear during compilation.

**To Reproduce**
Given this `entity`:

```
entity Alamakota {
    field left: Int = 1;
}
```

This code works as expected:

```
function decr(ala: Alamakota): Alamakota
    ensures $return.left == ala.left - 1;
{
    return ala.update(left = ala.left - 1);
}

...

var a = Alamakota@{};
var changed = decr(a);
```

While this one does not:

```
function decr(ref ala: Alamakota): Alamakota
    ensures $return.left == ala.left - 1;
{
    ala = ala.update(left = ala.left - 1);
    return ala;
}

...

var a = Alamakota@{};
var changed = decr(ref a);
```

**Expected behavior**
I expect both examples to work properly, i.e. compile and run.

**Screenshots**
This is a stack trace:

```
$ node bin/runtimes/exegen/exegen.js b.bsq
Compiling Bosque sources in files:
b.bsq
...
Transpiling Bosque assembly to C++ with entrypoint of NSMain::main...
Trace: TypeError: Cannot read property 'callers' of undefined
    at [...]\workspace\BosqueLanguage\impl\bin\compiler\mir_callg.js:74:51
    at Set.forEach (<anonymous>)
    at topoVisit ([...]\workspace\BosqueLanguage\impl\bin\compiler\mir_callg.js:74:16)
    at [...]\workspace\BosqueLanguage\impl\bin\compiler\mir_callg.js:99:9
    at Array.forEach (<anonymous>)
    at Object.constructCallGraphInfo ([...]\workspace\BosqueLanguage\impl\bin\compiler\mir_callg.js:97:17)
    at Function.emit ([...]\workspace\BosqueLanguage\impl\bin\tooling\aot\cppdecls_emitter.js:132:36)
    at Immediate._onImmediate ([...]\workspace\BosqueLanguage\impl\bin\runtimes\exegen\exegen.js:73:55)
    at processImmediate (internal/timers.js:456:21)
    at Immediate._onImmediate ([...]\workspace\BosqueLanguage\impl\bin\runtimes\exegen\exegen.js:163:17)
    at processImmediate (internal/timers.js:456:21)
Error -- TypeError: Cannot read property 'callers' of undefined
Done with executable -- a.exe
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Bosque Version: master

**Additional context**
It seems to me that just by adding the `ref` keyword in the parameters list you can reproduce this issue. I have tested it in many ways and it looks like so.

**Comment by mrkmarron** [comment]
Yes, you are right this is a bug and thanks for reporting it. 

The problem is in the ensures clause the ref variable should refer to the final value but you might also want to refer to the input value as well. Unfortunately, there was no consistent syntax for this at the time and I just dropped in a TODO placeholder comment. 

In my [hacking branch](https://github.com/mrkmarron/BosqueLanguage/tree/gc) I am trying out a `$` binder syntax to fix both this bug and the underlying problem. The result should look something like:
```
function inc(ref x: Int): Bool 
  ensures x =$$ x + 1;
{
  x = x + 1;
  return true;
}
```
