### ISSUE TITLE
Probable typo in whitepaper

### ISSUE THREAD

**Issue by ianfm** [Microsoft/BosqueLanguage#4]
Not sure if this is the best place to put this, but I believe I found a minor typo on page 3 of the Bosque whitepaper and thought the author might appreciate it if I reported it somewhere.

Relevant sample code:
"""
/ / c a l l s with e x p l i c i t arguments
var x = nsum ( 0 , 1 , 2 , 3) ;
[...]
/ / c a l l s with spread arguments
var l = @[0 , 1 , 2 , 3 ] ;
var y = nsum ( 0 , . . . l ) ; / / same as x
"""

Followed by the remark I believe is erroneous:
"""
Semantically, the call nsum(0, ...l) is the same as nsum(0, l[0], l[1], l[2]) 
"""

Suggested correction:
Given that l has 4 elements, I would expect that nsum(0, ...l) is equivalent to nsum(0, l[0], l[1], l[2], l[3]), not nsum(0, l[0], l[1], l[2]), which would be nsum(0, 0, 1, 2) and therefore not equal to x.

Additional note in case this reaches the author:
I would caution against the use of the letter l as a variable name given that it is effectively indistinguishable from the number 1 in all of the typefaces I have seen thus far in the paper. Since both are used as arguments in the example I reference above, changing the variable name to something other than l would improve clarity!

I hope this helps!

**Comment by mrkmarron** [comment]
Hi this is Mark (the author). Thanks for finding the mistake and the comments on variables and readability. I agree with both points and will update the report shortly.

**Comment by ianfm** [comment]
Great! I'm looking forward to finishing the paper. We could all use a little less accidental complexity in our lives.

**Comment by mrkmarron** [comment]
Great, and if you have any other thoughts or comments please share them here or via email.
