### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by rafdol** [Microsoft/BosqueLanguage#42]
Probably you have error in **README.md** in **Update y-value on point Record** example:

`updateY(@{x=1, y=2, z=3}, 5) //@{x=-1, y=5, z=3}`

If `updateY` update y-value why x-value changed from `1` to `-1`?

**Comment by nealmcb** [comment]
Observe that the code also sets x=-x. So the name is the confusing thing.

**Comment by mrkmarron** [comment]
Thanks for raising this issue. This was definitely a problem and I have renamed the method + updated the associated text. 

Closing this issue now but feel free to reopen if you think there are any more problems.
