### ISSUE TITLE
Question: Why bsl when there is already TypeScript

### ISSUE THREAD

**Issue by yuqingc** [microsoft/BosqueLanguage#50]
May I ask some questions?

According to the `test` script filed in the "tictactoe" example program, bsl is compiled to JavaScript as its target language. Why do we need another "compiled-to-JS" language when there is already TypeScript? 

Is it the final goal of this language that bsl is always compiled to js? If the answer is "yes", why don't we improve those features on TS?
Is there a plan that we make a runtime for bsl, or that bsl is compiled to binary code in the future?

**Comment by naddeoa** [comment]
I have similar questions around the goals of Bosque. The goal is described generically as "improved developer productivity, increased software quality", which is the goal of most languages, but I assume there must be something that the language designers are trying to achieve from the point of view of developer experience when compared with specific languages today, or perhaps some niche that it could fill that TypeScript and F# (and others) don't or won't fill.

Are people justified in asking those types of questions at this point or should this really be looked at as a fun research effort? Even in that case, what was the original inspiration?

**Comment by chriskuech** [comment]
I would love if Bosque is just a skunkworks branch of TypeScript and if these features, like `requires`, were pushed asap into TypeScript

**Comment by mrkmarron** [comment]
We actually compile to a intermediate code and use an interpreter written in TypeScript to execute the code. Later we would like to have other execution options like WASM or native binaries.

At this point in time the project is definitely focused on exploring concepts in the language design space. This gives flexibility to look at things from new perspectives. As time goes on we will see what works, what doesn't, if people actually want to write non-trivial applications in Bosque, and what other languages can learn from our experience.

For more info on the inspiration I would definitely take a look at the [technical report](https://www.microsoft.com/en-us/research/uploads/prod/2019/04/beyond_structured_report_v2.pdf).
