### ISSUE TITLE
Default values for function arguments

### ISSUE THREAD

**Issue by spixi** [microsoft/BosqueLanguage#51]
At the moment, Bosque only supports optional arguments, which are in fact implemented as arguments with the default value of `none`. There is no way to set any other default value.

Given the functions
```
function fun1(a: Int? = none; b?: Int, ...c: List[Int])
function fun2(a: Int = 42, b: Int, c?: Int, ...d: List[Int] = @[47, 11])
```

The following code
```
fun1(1)
fun1(1,2)
fun2(1)
fun2(1,2,3)
fun2(a=1,2,3)
```

should be equivalent to
```
fun1(a=none, b=1, c=none)
fun1(a=none, b=1, c=@[2])
fun2(a=42, b=1, c=none, d=@[47, 11])
fun2(a=42, b=1, c=2, d=@[3])
fun2(a=1, b=2, c=3, d=@[47, 11])
```
The rest operator should always absorb superfluous arguments, when all other arguments have an assigned value.

**Comment by mrkmarron** [comment]
Hi @spixi, thanks and I agree that your proposal is more flexible than what is currently implemented. 

The initial thinking was that we wanted to start with simpler semantics -- optional values are always default to `none` and optional/rest parameters can't be mixed. But as we get more experience we definitely might want to make changes as you suggest.

**Comment by mrkmarron** [comment]
Merging with issue #103
