### ISSUE TITLE
Add this language to learnxinyminutes.com

### ISSUE THREAD

**Issue by dumblob** [Microsoft/BosqueLanguage#52]
Please add this language to https://learnxinyminutes.com/ - head to https://github.com/adambard/learnxinyminutes-docs .

**Comment by mrkmarron** [comment]
We are currently focused on the exploring design concepts and research prototyping. So, until the language is more stable I don't think it is a good candidate for a tutorial yet. 

Thanks for the link and in the future we may add Bosque to the list.
