### ISSUE TITLE
Question: How to submit CLA

### ISSUE THREAD

**Issue by RyanAFinney** [Microsoft/BosqueLanguage#53]
Hello,

I have the CLA downloaded, filled out and signed, but cannot find where to send it on cla.microsoft.com.

Where should I submit this to allow me to contribute to this project? 

Thanks,

Ryan

**Comment by radu-matei** [comment]
(Not a maintainer / contributor to this project, but we also use the Microsoft CLA bot on our repositories).

When you submit a pull request, if your signed-in user didn't accept the CLA, you will get a link from the CLA bot to accept the agreement.

> Sign the CLA
> When you contribute to a Microsoft open source project on GitHub with a new pull request, a bot will evaluate whether you have signed the CLA. If required, the bot will comment on the pull request, including a link to this system to accept the agreement. 
([source](https://cla.opensource.microsoft.com/))

**Comment by RyanAFinney** [comment]
Thanks!
