### ISSUE TITLE
Unclear list processing examples

### ISSUE THREAD

**Issue by LiquidLemon** [Microsoft/BosqueLanguage#54]
I'm not quite sure what's going on in the examples of operations on lists:
```
var v: List[Int?] = List@{1, 2, none, 4};
  
//Chained - List@{1, 4, 16}
v.filter(fn(x) => x != none).map[Int](fn(x) => x*x)

//Piped none filter - List@{1, 4, none, 16}
v |> filter(fn(x) => x != none) |> map[Int](fn(x) => x*x)

//Piped with noneable filter - List@{1, 4, 16}
v |??> map[Int](fn(x) => x*x)

//Piped with none to result - List@{1, 4, none, 16}
v |?> map[Int](fn(x) => x*x)
```

First of all I have not been able to run any of those. I looked at the other code examples and realized that `->` seems to be the actual method call operator but that still did not help me. Execution fails with the error `fail with exception -- TypeError: Cannot read property 'invoke' of undefined` which I imagine comes from somewhere in the interpreter internals. Is this not implemented yet?

Another thing is that I'm pretty sure that the second example should return `List@{1, 4, 16}` since it manually filters out `none` values.

**Comment by mrkmarron** [comment]
Hi @LiquidLemon, you are absolutely correct. Thanks for pointing this out. I have updated the example text. The pipeline operator is also not fully implemented in this initial release so I have opened issue #58 to document this and track when it is done.

Thanks again.

**Comment by LiquidLemon** [comment]
Okay, thanks for clarifying that.
