### ISSUE TITLE
Question: Is this not Erlang but with altered syntax & some nomenclature changes?

### ISSUE THREAD

**Issue by ramriot** [Microsoft/BosqueLanguage#56]

**Comment by mrkmarron** [comment]
This needs a bit more elaboration. Closing the issue.

Please see the [paper ](https://www.microsoft.com/en-us/research/uploads/prod/2019/04/beyond_structured_report_v2.pdf) for more detail on the core concepts and feel free to reopen if there are more detailed questions.
