### ISSUE TITLE
Variable name '_result_' is not defined

### ISSUE THREAD

**Issue by hearot** [Microsoft/BosqueLanguage#61]
I tried to use the [ensures - "post-condition" feature](https://github.com/Microsoft/BosqueLanguage/blob/master/docs/language/overview.md#012-errors-and-checks) because I think it's one of the best features Bosque has got, but I got an error: `Variable name '_result_' is not defined`.

I used `node bin/test/app_runner.js angles.bsq` to run the code. I'm using Windows 10.

<details>
<summary>Code - angles.bsq</summary>

```bosque
namespace NSMain;

entity Angle {
    field degrees: Int = 0;
    field primes: Int = 0;
    field seconds: Int = 0;

    method normalized(over360?: Bool): Angle 
        ensures _result_.primes < 60;
        ensures _result_.seconds < 60;
    {
        var! seconds = this.seconds % 60;
        var! primes = this.primes + (this.seconds / 60) % 60;
        var! degrees = this.degrees + (this.primes + (this.seconds / 60)) / 60;
        
        if (over360 && degrees > 360) {
            degrees = 360;
        }

        return Angle@{degrees, primes, seconds};
    }
}

entrypoint function main(): Angle {
    var angle = Angle@{0, 60, 60};

    return angle->normalized();
}
```
</details>

**Comment by mrkmarron** [comment]
Hi @hearot, there was a mistake in the documentation ( PR #65 ). `_result_` should be `_return_`. I made this change in your example and was able to run it successfull. Sorry for the confusion. 

It is great to see someone experiment with writing some Bosque code. If you get something you think is interesting (even like the tic-tac-toe example) please consider opening a PR to include it in our set of test/example apps.

**Comment by hearot** [comment]
Thank you. I'll probably open a PR as soon as I finish writing the example.

**Comment by mrkmarron** [comment]
Great, and if you run into any other problems or sources of confusion please don't hesitate to open an issue.
