### ISSUE TITLE
Question: Visibility

### ISSUE THREAD

**Issue by Andersmholmgren** [microsoft/BosqueLanguage#67]
I've seen the `hidden` keyword on some method examples.

1. what is the scope of this visibility? Class? Namespace?
1. how would a `hidden field` work with the way constructors work?

**Comment by mrkmarron** [comment]
Good question. The design of visibility rules for fields/members is an open issue. 

I am not a huge fan of the standard public/private/protected model. With immutablility the need for protecting from modification is much reduced and, personally, I always seem to end up fighting with the visibility options.

I wanted to experiment a bit with a convention driven model for visibility where all fields, even `hidden`, can be accessed from anywhere. However, the `hidden` modifier would (1) prevent the field from showing in autocomplete lists outside of the defining type familty and (2) would indicate that this field was internal and subject to change (so anyone using it would do so at their own risk).

**Comment by Andersmholmgren** [comment]
I agree that there is no compelling reason to prevent access to `hidden` fields/members. As long as the tooling makes it clear and potentially lint rules could be configured to warn / error then that is enough IMO.

How would you handle `hidden fields` that are derived from other fields? 
I don't think a `factory` function would work unless you can enforce that it is always called.

There doesn't seem to currently be any concept of a function that is invoked during construction after the other fields are set, nor any `getter` that could calculate the field. 
I guess you could do it as a method like `getFoo`
