### ISSUE TITLE
language syntax is not totally incomprehensible

### ISSUE THREAD

**Issue by billwoo** [Microsoft/BosqueLanguage#7]
Clearly, great progress has been made towards inscrutability, but there are still areas where increased semantic obtuseness can be attained. The use of even a few standard operators ... from the C/C++/C# canon ... like the assignment operator, can be made much more difficult to use.

How about:    <= makevar ::string:: => ~some string~ 

The use of Greek letters from APL could also be considered.

**Comment by mrkmarron** [comment]
It is always a challenge to find the good ballance in syntax. Perhaps there are some specific operators or alternative syntax options that you can expand on.

**Comment by merriam** [comment]
Kidding aside, maintenance costs are by token, regardless of if that token is punctuation or an identifier.  The lambda statement of `fn(x) => x*2` costs 8 while `x => x*2` costs 5.

While individual syntax items could be addressed, a more efficient choice might be to publish your priorities in the language.  As a reference, the Zen of Python provides a concise and ordered list of language priorities.

**Comment by mrkmarron** [comment]
Thanks for the ideas. Issue #14 is now setup to have a more general discussion around some of these issues.
