### ISSUE TITLE
TypeError: Cannot read property 'invoke' of undefined

### ISSUE THREAD

**Issue by hearot** [Microsoft/BosqueLanguage#70]
I was trying to code my own `max` function in Bosque when I got this: `TypeError: Cannot read property 'invoke' of undefined`.

I'm using Windows 10 and I used `node bin\test\app_runner.js over.bsq` to launch the script.

<details>
<summary>Output</summary>

```
Reading app code...
Executing app code...
fail with exception -- TypeError: Cannot read property 'invoke' of undefined
```

</details>

<details>
<summary>Code - over.bsq</summary>

```bosque
namespace NSMain;

function max(x: Int, y: Int): Int
    ensures _return_ == x || _return_ == y;
{
    if (x >= y) {
        return x; 
    } else {
        return y;
    }
}

function main(): Int {
    var x = 10;
    var y = 20;

    return max(x, y);
}
```

</details>

**Comment by mrkmarron** [comment]
The `entrypoint` function main should be annotated as such. After the changes below it runs and produces the output `20`.

```
entrypoint function main(): Int {
    var x = 10;
    var y = 20;

    return max(x, y);
}
```

**Comment by hearot** [comment]
Fixed, thank you.
