### ISSUE TITLE
Issue on Language

### ISSUE THREAD

**Issue by zzdpk2** [microsoft/BosqueLanguage#71]
Does Bosque support Chinese characters?

**Comment by hearot** [comment]
I tried and it does. 

<details>
<summary>Output</summary>

```
Reading app code...
Executing app code...
Done with -- "我爱北京天安门"
```

</details>

<details>
<summary>Code - chinese.bsq</summary>

```bosque
namespace NSMain;

entrypoint function main(): String {
    return "我爱北京天安门";
}
```

</details>

**Comment by mrkmarron** [comment]
Seems to be answered.
