### ISSUE TITLE
return if statement request

### ISSUE THREAD

**Issue by MairwunNx** [microsoft/BosqueLanguage#74]
I have seen similar syntactic sugar in some languages, for example Kotlin, I would like to see it in `BosqueLanguage`, I think it would not be a bad idea for a language design.

###### Example:

```
function abs(x: Int): Int {
    if(x < 0) {
        return -x;
    }
    else {
        return x;
    }
}
```

###### If use return if statement:

```
function abs(x: Int): Int {
    return if(x < 0) {
        -x;
    }
    else {
        x;
    }
}
```

###### Example 2:

```
function absy(x?: Int): Int {
    if(x == none) {
        return 0;
    }

    return {
        var! y = x;
        if(y < 0) {
            y = -y;
        }
        yield y;
    }
}
```

###### If use return if statement:

```
function absy(x?: Int): Int {
    return if(x == none) {
        0;
    }
    else {
        var! y = x;
        if(y < 0) {
            y = -y;
        }
        y;
    }
}
```

**Comment by hearot** [comment]
I love the `abs` example. Awesome!

**Comment by mrkmarron** [comment]
Thanks for the examples. This is a planned feature, issue #26 which would allow `if` as well as `match` to be used this way.
