### ISSUE TITLE
return expression in method

### ISSUE THREAD

**Issue by MairwunNx** [microsoft/BosqueLanguage#76]
It would not be bad to implement, because the code will become a bit cleaner. I observed this syntax in Kotlin and in C#, I would be happy and I would think users would be happy if contributors implemented a similar feature

###### Example: 

```
namespace NSMain;

entrypoint function main(): Int {
    return add(-2, -3);
}

function add(x: Int, y: Int): Int {
    return x + y;
}
```

###### With return lambda expression:

```
namespace NSMain;

entrypoint function main(): Int => add(-2, -3);

function add(x: Int, y: Int): Int => x + y;

```

###### Or with using = operator

```
namespace NSMain;

entrypoint function main(): Int = add(-2, -3);

function add(x: Int, y: Int): Int = x + y;

```

Currently interpreter not understand such expressions.

**Comment by hearot** [comment]
Take a look at https://github.com/Microsoft/BosqueLanguage/blob/master/docs/language/overview.md#56-lambda-constructors

**Comment by MairwunNx** [comment]
@hearot I saw those examples, unfortunately they are not quite used as I intended.
I meant expressions return specifically with methods.

With examples with link what you dropped upper it be like:

```
entrypoint function main(): Int {
    var result = fn(x: Int, y: Int): Int => x + y;
    return result(-2, -3);
}
```

**Comment by mrkmarron** [comment]
Closing and referencing issue #14 for future discussion.
