### ISSUE TITLE
Will there be a dotnet compiler? 

### ISSUE THREAD

**Issue by dotChris90** [Microsoft/BosqueLanguage#79]
A stupid question maybe but... since dotnet core gains great attention it would be nice to see some more languages joining.

or shall it be compiled to native machine code?

**Comment by MairwunNx** [comment]
Currently i think it Bosque target on web. But i think in future it can used as language for dotnet, but I am not sure, considering what stage the language is at.

In the near future I think we should not hope so. 🤔

**Comment by clegoz** [comment]
Duplicate: #43
