### ISSUE TITLE
Optional record properties are not sound under the subtyping relationship

### ISSUE THREAD

**Issue by weswigham** [Microsoft/BosqueLanguage#8]
And allow exactly the kind of ambiguity and accidental complexity you seem to want to avoid. TypeScript itself has this problem and is part of why is has separate subtype (which optional-ness doesn't participate in) and assignable relationships.

Specifically, since `{x: Int, y?: Int} <: {x: Int} <: {x: Int, y?: String}` (also the other way around - this also destroys the desirable partial ordering you'd like the subtype relationship to have), aliasing can cause the type of a field to be "forgotten" and then replaced with a different, _incompatible_ type; creating potential unexpected behavior on the read of such a property.

You probably want to fix this as early as possible, so you're not stuck with an unsound relation ;)

**Comment by mrkmarron** [comment]
Hi Wes, I recall some of the challenges with records in TS. So, we specifically have _closed_ and _open_ record types. So, in Bosque `{x: Int, y?: Int} <: {x: Int}` is false while `{x: Int} <: {x: Int, y?: Int}` is true. 

If you want the open version you can have `{x: Int, y: Int} <: {x: Int, ...}` which is true. 

I think this addresses the concern you raise but let me know if you think I am missing something.

Thanks!

**Comment by weswigham** [comment]
> So, we specifically have closed and open record types

So by "closed", you mean "forbids subtypes with more keys" right? Ah, ok. I'd not noticed that when browsing the overview - it's not mentioned, but I assume this means you're not allowed to mix open types with optionality? Eg, `{x: Int, y?: Int, ...} <: {x: Int, ...} <: {x: Int, y?: String, ...}`

**Comment by weswigham** [comment]
Using just mostly the identities in the overview:
```
{f: Int, g: Bool} <: {f: Int, ...} <: {f: Int} <: {f: Int, g?: String}
```

Seems pretty bad though.

**Comment by narfanar** [comment]
Quoted from #9 :

> Why is this:
> 
>
```
{f: Int, g?: Bool} <: {f: Int} // false, why?
[Int] <: [Int, ?:Bool]  // true, why?
```
> 
> By ([Structural Type System](https://en.wikipedia.org/wiki/Structural_type_system)), it would seem to me that these (and similar ones) should be reversed.
> 
> Is there more info on Bosque's type system somewhere?

**Comment by weswigham** [comment]
@narfanar That would simply be because the typed are closed and thus do not admit subtypes which contain excess keys. (Be they tuple indexes or record keys.) I missed that in my initial reading; though a version of my supposition is still open for the open version of those types.[1] That means that the type `{x: Foo, y?: Bar}` is equivalent to (or should be - again, a little too in depth for the examples maybe, and I don't know if the relationships described cover optional/union equivalences) exactly `{x: Foo} | {x: Foo, y: Bar}`. As a member of that union, `{x: Foo}` is ofc a subtype of it.

[1]Specifically, `{x: Int, ...} <: {x: Int, y?: String, ...}` needs to be false in the example I gave above (if such types may be constructed), but weather that's the case is unclear, since `{x: Int} <: {x: Int, y?: String}` is true, and no example really covers it. :D

**Comment by narfanar** [comment]
```
{x: Int} <: {x: Int, y?: String}
```
But this makes no sense to me. Passing a value of type `T1` to a slot expecting type `T2` involves assuming that the value meant for its (non-existent, but expected) field `y?` to be `None`... How? Why?

TypeScript does something similar, by disallowing "excess properties" in `T1`. It's just a bit confusing, and not what I'd expect coming from languages like C++, where a subtype extends the functionality/fields of a supertype. Insight?

**Comment by weswigham** [comment]
> TypeScript does something similar, by disallowing "excess properties" (see here) in T1. 

It's a liiiiiitle different - a JS object literal can almost always be read as a closed type (since it's initially made with a well-known set of fields) and TS contextually determines to treat the type to which the literal is assigned as a kind of "closed" as well, since we'd observed it's _pretty much always an unintentional error when you pass extra properties with a literal because nobody usually actually needs open types_ (excepting, ofc, when an index signature is involved).

>  It's just a bit confusing, and not what I'd expect coming from languages like C++, where a subtype extends the functionality/fields of a supertype. Insight?

And that's still true of _open_ records, which match that intuition. You could say that in many languages "open" records are the default kind of record type, while closed may or may not even exist. TS doesn't have an exposed syntax for a closed record type (but does conceptualize them in checking for literal expressions), and Flow, for example, has closed record types, and is currently in the process of transitioning to closed-by-default declaration syntax.

It's worth noting that with type-level set negations a closed record is the roughly equivalent of the conjunction of the open version of the record with the negation of the root open record type, eg `{x: Int, ...} + not {...}` (were conjunctions of open records allowed), since any open record would not provide the second type, only a closed type providing the properties of the first type could satisfy both.

**Comment by mrkmarron** [comment]
You are right on the closed types.

You can use optionality with open types such as `{x?: Int, ...} <: {...}` but we will reject something like `{...} <: {y?: Bool, ...}` as a type error since there are values in `{...}` that cannot inhabit `{y?: Bool, ...}` e.g. `@{y: 5}`. 

As you mention things get very subtle if you have negation or intersection. So, we only allow unions of record or tuple types. Intersection is only supported for the nominal type system for the current time.

**Comment by weswigham** [comment]
> but we will reject something like {...} <: {y?: Bool, ...} as a type error since there are values in {...} that cannot inhabit {y?: Bool, ...} e.g. @{y: 5}.

Neat - I was unsure of this since when browsing through the code (as the docs didn't mention it yet and it doesn't follow obviously from any other relationships), all I could find was something that filtered optional and any-typed properties from the record type upon construction if it was open (leading me to believe that `{x?: Bool, ...}` was simplified to `{...}` upon construction, which seemed inaccurate (as `{...} <: {...}` is obviously true, yet `{...} <: {x?: Bool, ...}` shouldn't be)).

>Intersection is only supported for the nominal type system for the current time.

Yeah; despite that it's still unclear to me how given
```
concept D1 {
    field f: {x: Int}
}

concept D2 {
    field f: {y: Int}
}
```
that type `D1 + D2` seems to be unsatisfiable (and both cannot be provided by the same entity); but that's assuming that there's not some namespacing going on and D1.f and D2.f are actually separate fields.

**Comment by mrkmarron** [comment]
Yes, we have the standard diamond inheritance problem with concepts. The approach we currently have is a requirement that all possible resolutions are consistent with the declaring type so declaring the type `D1 + D2` should be a type error. 

I would like to get this written up more formally (and maybe try to submit somewhere). It would be great to include a compare/contrast with the TS type system.

**Comment by weswigham** [comment]
> so declaring the type D1 + D2 should be a type error.

Does that imply that declaring generics which could instantiate to such a type are an error (and are identified as such)? Or is it an error upon some form of instantiation to such types? Or can conjunctions of generics simply not be made at present?

**Comment by mrkmarron** [comment]
Yes, we currently do detection at instantiation time. The implementation needs improvement though.

**Comment by weswigham** [comment]
How do y'all handle assigning "fault" upon instantiation (on what span does an error get made)?

(Closing the issue since now I'm just asking questions and my original issue is long since addressed)

**Comment by mrkmarron** [comment]
Currently, we instantiate and expand all generic instantiations for typechecking and compilation (ala C++ templates). We don't track the expansion path so the error messages are definitely not good. Also we will need to see if this starts to become a performance problem for interactive feedback.

**Comment by narfanar** [comment]
> And that's still true of _open_ records, which match that intuition. You could say that in many languages "open" records are the default kind of record type, while closed may or may not even exist. TS doesn't have an exposed syntax for a closed record type (but does conceptualize them in checking for literal expressions), and Flow, for example, has closed record types, and is currently in the process of transitioning to closed-by-default declaration syntax.

So that covers that part.

But still, optional types seem magical here. Or, given they're just `T | None`, `None` itself is special? So any `T | U | <blah> | None` gets the same treatment?
