### ISSUE TITLE
Language name questions

### ISSUE THREAD

**Issue by cyungmann** [microsoft/BosqueLanguage#80]
What does the name mean and how is it pronounced? Is it related to https://en.wikipedia.org/wiki/Bosque? Thanks!

**Comment by mrkmarron** [comment]
The name is a Spanish word for forest. In the Southwest US (where I am from) it is the forest by a river as described in the wikipedia page. No deep meaning behind the name choice.

**Comment by brunolpw** [comment]
> 
> 
> The name is a Spanish word for forest. In the Southwest US (where I am from) it is the forest by a river as described in the wikipedia page. No deep meaning behind the name choice.

In Portuguese "bosque" is a little florest.
pt* Em português "bosque" é uma pequena floresta.
