### ISSUE TITLE
Type and implementation separation?

### ISSUE THREAD

**Issue by fendy3002** [microsoft/BosqueLanguage#81]
Are there any plan to separate type definition and code implementation? In typescript I usually do something like this:

```javascript
interface myType {
  (myInput: { name: string, age: number }): { id: number, ticket: string }
}
const myFunc: myType = (myInput) => {
  // return {id: id, ticket: ticket};
}
```

It makes implementation cleaner though less verbose.

**Comment by mrkmarron** [comment]
You can do the same thing in Bosque with `concept` and `entity` -- roughly they are equvalent to `interface` and `class`. 

```
concept Foo {
    abstract method m(x: Int): Int;
}

entity FooImpl provides Foo {
    override method m(x: Int): Int {
        return x + 1;
    }
}
```

No current plans to do more separation, like C++ `.h` vs `.cpp` files though.

**Comment by mrkmarron** [comment]
Seems to be answered. Please reopen if needed.
