### ISSUE TITLE
passing nominal as structural argument

### ISSUE THREAD

**Issue by Andersmholmgren** [microsoft/BosqueLanguage#83]
Somewhat related to #81 

It would be nice to be able to pass nominally typed objects to functions that expect structural types if they have the same shape. e.g

```
entity Bar {
    field bar: String;
}

function getBar(theBar: {bar: String}): String {
    return theBar.bar;
}

entrypoint function main(): String {
    var structuralBar = @{bar="hi"};
    var nominalBar = Bar@{bar="hi"};
    return getBar(structuralBar);
    // return getBar(nominalBar); // ERROR: Parameter theBar expected argument of type {bar:NSCore::String[NSCore::Any]} but got NSMain::Bar"]
}
```

**Comment by mrkmarron** [comment]
Yes, I experiemented with this idea a bit previously but I never had something I was satisfied with. Some issues that came up:
* With the update semantics if I have an object and update a field, do the record properties get copied as well?
* How should property/field shaddowing work?

It seemed too much to try in the first version but would be interested in any design ideas.

**Comment by Andersmholmgren** [comment]
If I understand you correctly I would expect similar semantics to say Typescript

```
entity Bar {
    field bar: String;
    field foo: Int = 2;
}

function getBar(theBar: {bar: String}): {bar: String} {
    return theBar<~(bar="there");
}

entrypoint function main(): {bar: String} {
    var structuralBar = @{bar="hi"};
    var nominalBar = Bar@{bar="hi"};
    return getBar(structuralBar); // @{ bar="there" }
    // return getBar(nominalBar); // Bar@{ bar="there", foo=2 }
}
```

Can you give an example of the shadowing issue?

**Comment by mrkmarron** [comment]
Sure, suppose I have the entity:
```
entity Foo {
    field f: Int;
}

function addf(r: {...}): {...} {
    return r<~(f=true);
}

var a = Foo@{f=3};
var b = addf(foo);

_debug(b.f); //is the value from the field (3) or property (true) or was there an error at the update? 
```

**Comment by mrkmarron** [comment]
Closing as there doesn't seem to be more going on here. Please reopen if needed.
