### ISSUE TITLE
How to declare a namespace

### ISSUE THREAD

**Issue by hearot** [Microsoft/BosqueLanguage#85]
@MairwunNx and I were thinking about how namespaces can be declared. While I was writing the two examples, I noticed that all namespaces start with `namespace NS` and then are followed by a string and a semicolon (for example: `namespace NSMain;`).

Will this be the final implementation or is it just a primitive way to declare namespaces? Why do we have to write `NS` at the beginning of the namespace?

**Comment by mrkmarron** [comment]
Currently the language is a bit strict about naming conventions:
* namespaces all start with NS
* type names all start with a capital
* template types are a single letter T, U, ...
* fields, methods, variables, properties, etc. all start with lowercase or `_` (single `_` is reserved)

The design of the namespacing and packaging are in flux ( issue #22 ) and namespace management should be part of this discussion.

**Comment by hearot** [comment]
Got it, thank you.
