### ISSUE TITLE
Add a new issue and pr template

### ISSUE THREAD

**Issue by abhinavsagar** [Microsoft/BosqueLanguage#86]
Currently the project is not having an issue and pull request template.
Adding one helps in having standardized information when submitting a pr or an issue.

**Comment by hearot** [comment]
I agree.

**Comment by mrkmarron** [comment]
Thanks for mentioning this. There has been more interest than I was anticipating so some templates to help organize will be very useful. I have just added an initial set. Please take a look and see if there are any suggestions.

**Comment by abhinavsagar** [comment]
@mrkmarron This could be closed.
