### ISSUE TITLE
multiline comment feature

### ISSUE THREAD

**Issue by MairwunNx** [Microsoft/BosqueLanguage#90]
I may be doing something wrong, but I have an interpretation error when using multi-line comments. I also noticed that only single-line comments are used in core.bsq, this is not very nice.

I came to the conclusion that they were simply not added yet, I hope that this will be added in the following fixations.

**Comment by mrkmarron** [comment]
Yeah, no multi-line comments yet. Definitely something to get added.

Adding a enhancement tag and, since the code changes are limited to the lexer/parser this is a good issue starter issue if someone wants to try it out.

**Comment by clegoz** [comment]
I've looked specs but I couldn't find any info about multi-line comments. Anyway, I've made simple assumption like multi-line comments must start with `/*` and end with `*/` and I've tried few patterns according to this.

`\/\*[\s\S]+?\*\/` - This is lazy. Therefore for every character (except wildcard), regex engine has to backtrack all the time.
`\/\*(?:[^\*]*\*+)+?\/` - This one is better. Regex engine backtracks only if the non-capturing group contains multiple wildcards.

Do you have any thoughts? Or better alternatives?

**Comment by hearot** [comment]
> I've looked specs but I couldn't find any info about multi-line comments. Anyway, I've made simple assumption like multi-line comments must start with `/*` and end with `*/` and I've tried few patterns according to this.
> 
> `\/\*[\s\S]+?\*\/` - This is lazy. Therefore for every character (except wildcard), regex engine has to backtrack all the time.
> `\/\*(?:[^\*]*\*+)+?\/` - This one is better. Regex engine backtracks only if the non-capturing group contains multiple wildcards.
> 
> Do you have any thoughts? Or better alternatives?

I agree with you.

**Comment by mrkmarron** [comment]
I like the `/* ... */` design. I would lean towards the more efficent regex. We can make some changes later if we find something else that we like more. Might also want to take a quick look at the TypeScript [repo](https://github.com/Microsoft/TypeScript) to if there is something in how they do comments that we like

**Comment by clegoz** [comment]
I looked the TypeScript source code. It's hard to take an inspiration because they're not using regex but it really helped me with test cases. 

Anyway, I've modified existing pattern. You could see it [here](https://github.com/clegoz/BosqueLanguage/blob/99f806957ff4998855e5f5f90861869c9e051426/ref_impl/src/ast/parser.ts#L252).

Before making a PR, I need an opinion. Lets say we have a file which contains `/*` but does not contain `*/`. In this case we have to throw compilation error like `*/ expected` but since we do not support throwing exception in lexer, we can't throw.

What should we do?

e.g.:
```
/*
entrypoint function exampleMethod(): Int {
    ...
}
```

**Comment by mrkmarron** [comment]
The lexer has an "[Error]" [token](https://github.com/Microsoft/BosqueLanguage/blob/bf9920a89bc52badc2ecdf82249ffd22a2312b49/ref_impl/src/ast/parser.ts#L118) which can be inserted to clean up mismatched things like this. The compiler will later see this token and can either try to recover or just give up with an error. So, as a simple first version, I would eat everything after the mismatched `/*` and insert an error token in the stream.
