### ISSUE TITLE
Purpose of `@`?

### ISSUE THREAD

**Issue by illeatmyhat** [microsoft/BosqueLanguage#92]
Why is initialization prepended with an `@`?

**Comment by mrkmarron** [comment]
The hope was to use the `@` symbol consistently in the syntax whenever a tuple/record/object was being constructed. Also helps distinguish the type `{f: Int, g: Int}` from the creation of a value of the type `@{f=3, g=2}`.

**Comment by wandyezj** [comment]
I see `@` used in the following way:

```
function update(point: {x: Int, y: Int, z: Int}, value: Int): {x: Int, y: Int, z: Int} {
    return point<~(y=value, x=-point.x);
}

update(@{x=1, y=2, z=3}, 5) //@{x=-1, y=5, z=3}
```

Would it make sense to make this more like TypeScript objects? (see below)

```
function update(point: {x: Int, y: Int, z: Int}, value: Int): {x: Int, y: Int, z: Int} {
    return {x: -point.x, y: value, z: z};
}

update({x: 1, y: 2, z: 3}, 5) // {x: -1, y: 5, z: 3}
```

It would seem to be more intuitive to new users to recycle existing syntax.

Is there some point I am missing?
