### ISSUE TITLE
How do you do i+=2 if there is no for loop

### ISSUE THREAD

**Issue by gino07172002** [microsoft/BosqueLanguage#93]
In other languages, if I want to do really simple downsampling in the image process. I can just use

for(int i=0;i<some_number;i+=2)

how to do it if there is no for loop.

**Comment by Myrddyn** [comment]
In languages with a functional paradigm, you tend not to use for loops as they imply reassignment of the iterator variable. Instead, there are functors such as map() or filter() that take a function as parameter, and apply the function on each element of the array.

In your case, you would likely use filter() to get an array half the size :
downsampledArray = initialArray.filter( fn(index, value) => index%2 == 0)

**Comment by fsencinas** [comment]
High level functors and recursion in some cases.

**Comment by mrkmarron** [comment]
Hi @gino07172002, thanks for this question. With the current collections library API it is not really obvious how to do this and we need to make sure the standard collections library provides this type of support. I have opened issue #103 as a meta-tracker for this and other similar issues.

For your case the fix will be to add an API that is `mapWithIndex` and `filterWithIndex` for the `List` class that will allow you to write (similar to what @Myrddyn suggested):
```
function downSample(image: List[Int]): List[Int] {
    return image.filterWithIndex(fn(index, value) => index % 2 == 0);
}
```

**Comment by wandyezj** [comment]
Would it make sense to copy the syntax of the [JavaScript filter method](https://www.w3schools.com/jsref/jsref_filter.asp)?

array.filter(function(currentValue, index, arr), thisValue)

**Comment by mrkmarron** [comment]
Merging with issue #103
