### ISSUE TITLE
Riparian - A package manager for Bosque

### ISSUE THREAD

**Issue by hearot** [microsoft/BosqueLanguage#95]
**Riparian would solve all the package issues.**
Riparian ([Wikipedia](https://en.wikipedia.org/wiki/Riparian_zone)) would be the package manager for Bosque with which you can install, update & publish packages. You can find the proposal on [hearot/riparian](https://github.com/hearot/riparian).

**Comment by Hritam-cse** [comment]
I think **Riparian** would be great.❤️

**Comment by Xh4H** [comment]
I would like to call each "package" a "tree".

**Comment by mrkmarron** [comment]
Thanks for sharing that. Can you breifly summarize some of the key features you think this package manager should provide and, if possible, how they relate to an existing system like NPM, cargo, or, nuget. 

Specifically, I want to think if our goal is taking the learnings and best practices of of previous package managers and adopting them for Bosque. Or are the new there new/better things we can do here?

**Comment by aarroyoc** [comment]
If you want to follow Spanish names, it would be "Ribera"

**Comment by hearot** [comment]
@aarroyoc That sounds awesome

**Comment by hearot** [comment]
I'm gonna create the description in few days!

**Comment by orcmid** [comment]
Laughing, aside: Thank you for helping me understand the intended meaning of Bosque as a woodlands situated on a riparian plain.  What is the waterway waters such woodlands called?  Arroyo?

**Comment by wandyezj** [comment]
It might be convenient if prevalent package managers could work with Bosque. This could substantially save on development, infrastructure, education, and maintenance costs. As improvements are made to existing package managers, Bosque would be able to take advantage of these improvements.

**Comment by mrkmarron** [comment]
Merging with issue #22
