### ISSUE TITLE
Structural Design failure

### ISSUE THREAD

**Issue by StephanVerbeeck** [Microsoft/BosqueLanguage#98]
After learning a batch of new languages the last decade like Swift and Kotlin and Golang and Rust, I came across this one and after a single look at the Code Snippets I can tell you that there is a fatal reasoning error (bug) behind the concept.  The bug is not in the software but in the syntax.  If the whole purpose was to create an easier and more readable syntax then I can tell you that **the code snippets** themselves already demonstrate complexity and unreadability beyond the complexity of C++.

As such there is no arguable reason to pursue this endeavor further.

With my apologies for bluntly pointing out what should be obvious.

**Comment by hearot** [comment]
What do you think about #84?

**Comment by StephanVerbeeck** [comment]
I concur with the more elaborate explanation in issue #84.

I also understand the need to cleanup JavaScript and that TypeScript is not the final answer to that quest.
I have been deeply involved in language design the past years and do not judge based on first impressions.  There is a need for a new language that runs both as compiled and as interpreted without syntax difference.  And such a language needs to be typed and have limited support for templates, classes, interfaces and such.  The closest matching this would currently be GOlang although it too has some mistakes that need cleaning up (for some it already be to late).

One major rule to follow when creating a more logical syntax is that REQUIREMENT ONE is that there is only one type of syntax (meaning that all language elements like loops and conditions and declarations all have to look like simple function calls.

So to have a separate syntax for a FOR and for an IF is from the start already introducing mistakes and exceptions.

Some of the more aggressive attempts to create the perfect language (e.g. Rust) are based on single assumptions that eventually will prove to be incorrect and introduce impractical constraints in real life programming.  The existing established order (C++/C#/Java) allow each programmer to establish its own (template)library creating a jungle of divers implementations and a zillion of glue-code at the boundaries of those different philosophies.

So yes there is need for something new but I (my personal opinion) think that the world is better served bundling forces behind a single project (e.g. GOlang) than each time come up with something new that has great ideas but fails the implement the basic stuff that is not part of these improvements.

**Comment by Hritam-cse** [comment]
I also agree that, the code snippets are look like a little bit complex and difficult to read.

**Comment by abhinavsagar** [comment]
@StephanVerbeeck I don't quite agree with you on this front. We should understand bosque is just in it's infancy. I think bosque has a couple of really good features which could make it stand out in future.

**Comment by StephanVerbeeck** [comment]
Yes it has a couple of really good features.
But none of which are not already up and running in other modern languages.
But futile attempts compared to what is already achieved  by other projects.
Bosque has no arguable reason to exist and pursuing its development is a waste of everybody's time and money.

**Comment by mrkmarron** [comment]
I am closing this as non-productive. Feedback is appreciated but this project operates under a [code of conduct](https://github.com/Microsoft/BosqueLanguage/blob/master/CONTRIBUTING.md) and participants are expected to engage in a _professional_ and _constructive_ manner.
