### ISSUE TITLE
Getting started in this repo

### ISSUE THREAD

**Issue by cbyad** [microsoft/BosqueLanguage#99]
I'm new to this repo that I found randomly in my google news feed.
I'm interrested with the project and want to contribute.
I seen the contributing files but didn't find anything to help me to getting started.
So what are for exemple features of Bosque core language that aren't yet implemented? 
Or simply what features can be quickly fixed or added.
Thanks!

**Comment by abhinavsagar** [comment]
Hi @cbyad Nice to hear that you are interested. You can start by reading [this](https://github.com/Microsoft/BosqueLanguage/blob/master/docs/language/overview.md) and then possibly solve one of the issues in this repo.

**Comment by cbyad** [comment]
Thanks @abhinavsagar :-)

**Comment by mrkmarron** [comment]
This seems to be resolved so marking it as closed.
